
import { WordData } from './types';

export const LEVEL_1_PART_2: WordData[] = [
  /* BLOQUE 1 (101-120) */
  {"id": "1-101", "hitza": "kimatu", "sinonimoak": ["inausi", "adaondu", "moztu"]},
  {"id": "1-102", "hitza": "lehortu", "sinonimoak": ["ihartu", "sikatu", "kabartu"]},
  {"id": "1-103", "hitza": "gogaikarri", "sinonimoak": ["nekagarri", "nekoso", "aspergarri"]},
  {"id": "1-104", "hitza": "ugazaba", "sinonimoak": ["etxejabe", "nagusi", "patroi"]},
  {"id": "1-105", "hitza": "gizatalde", "sinonimoak": ["talde", "kolektibo"]},
  {"id": "1-106", "hitza": "burujabetza", "sinonimoak": ["subiranotasun", "berjabetasun"]},
  {"id": "1-107", "hitza": "sinatu", "sinonimoak": ["izenpetu"]},
  {"id": "1-108", "hitza": "mintzo izan", "sinonimoak": ["hitz egin", "mintzatu", "berba egin", "solas egin"]},
  {"id": "1-109", "hitza": "muzin egin", "sinonimoak": ["mespretxatu", "arbuiatu", "gutxietsi"]},
  {"id": "1-110", "hitza": "oraintsu", "sinonimoak": ["berriki", "oraindik orain"]},
  {"id": "1-111", "hitza": "soil", "sinonimoak": ["xume", "xalo", "laño"]},
  {"id": "1-112", "hitza": "partaidetza", "sinonimoak": ["parte-hartze", "partaidetasun", "esku-harmen"]},
  {"id": "1-113", "hitza": "arrapala", "sinonimoak": ["aldapa", "aldats", "malda", "ike"]},
  {"id": "1-114", "hitza": "narriadura", "sinonimoak": ["degradazio"]},
  {"id": "1-115", "hitza": "ezagutzera eman", "sinonimoak": ["jakinarazi", "ezagutarazi"]},
  {"id": "1-116", "hitza": "matxura", "sinonimoak": ["aberia"]},
  {"id": "1-117", "hitza": "gaitasun", "sinonimoak": ["trebetasun", "trebezia"]},
  {"id": "1-118", "hitza": "herritartasun", "sinonimoak": ["hiritartasun", "hiritargo"]},
  {"id": "1-119", "hitza": "isilaldi", "sinonimoak": ["isilune"]},
  {"id": "1-120", "hitza": "onbideratu", "sinonimoak": ["oneratu"]},

  /* BLOQUE 2 (121-140) */
  {"id": "1-121", "hitza": "lelo", "sinonimoak": ["goiburu", "ikurritz", "eslogan"]},
  {"id": "1-122", "hitza": "hara-hona", "sinonimoak": ["batera eta bestera", "gora eta behera", "harat-honat"]},
  {"id": "1-123", "hitza": "tardatu", "sinonimoak": ["berandutu"]},
  {"id": "1-124", "hitza": "zarratu", "sinonimoak": ["itxi", "hetsi", "zerratu"]},
  {"id": "1-125", "hitza": "gainbehera", "sinonimoak": ["dekadentzia", "endekapen"]},
  {"id": "1-126", "hitza": "mamitsu", "sinonimoak": ["sakon", "adierazgarri"]},
  {"id": "1-127", "hitza": "ontasun", "sinonimoak": ["onezia", "onberatasun"]},
  {"id": "1-128", "hitza": "hurkotasun", "sinonimoak": ["hurbiltasun", "gertutasun"]},
  {"id": "1-129", "hitza": "gogorarazi", "sinonimoak": ["burura ekarri", "oroitarazi", "gomutarazi"]},
  {"id": "1-130", "hitza": "haserretu", "sinonimoak": ["sumindu", "muturtu", "koskatu", "zapuztu", "zipoztu"]},
  {"id": "1-131", "hitza": "jakinez", "sinonimoak": ["ezjakintasun", "ezjakite", "ezezgutza"]},
  {"id": "1-132", "hitza": "beharrizan", "sinonimoak": ["behar", "premia", "derrigortasun"]},
  {"id": "1-133", "hitza": "xahutu", "sinonimoak": ["eralgi", "zarrasteldu", "irion", "irazi"]},
  {"id": "1-134", "hitza": "gabetasun", "sinonimoak": ["hutsune", "peitu", "falta"]},
  {"id": "1-135", "hitza": "bermatu", "sinonimoak": ["garantizatu"]},
  {"id": "1-136", "hitza": "anoa", "sinonimoak": ["errazio"]},
  {"id": "1-137", "hitza": "mozkin", "sinonimoak": ["irabazkin", "etekin"]},
  {"id": "1-138", "hitza": "sehaska", "sinonimoak": ["kuma"]},
  {"id": "1-139", "hitza": "berretsi", "sinonimoak": ["konfirmatu"]},
  {"id": "1-140", "hitza": "lagundu", "sinonimoak": ["urgatzi", "sostengatu", "mesede egin", "sorotsi"]},

  /* BLOQUE 3 (141-160) */
  {"id": "1-141", "hitza": "sen", "sinonimoak": ["zentzu"]},
  {"id": "1-142", "hitza": "jakitun", "sinonimoak": ["jakintsu"]},
  {"id": "1-143", "hitza": "hurrupa", "sinonimoak": ["trago", "zurrutada", "zurrut", "zirrista"]},
  {"id": "1-144", "hitza": "eragotzi", "sinonimoak": ["galarazi", "oztopo egin", "behaztopatu"]},
  {"id": "1-145", "hitza": "sorrera", "sinonimoak": ["jatorri", "hasiera", "abiapuntu"]},
  {"id": "1-146", "hitza": "itzulikatu", "sinonimoak": ["nahastatu"]},
  {"id": "1-147", "hitza": "izurrite", "sinonimoak": ["izurri", "helde", "epidemia"]},
  {"id": "1-148", "hitza": "sumindu", "sinonimoak": ["berotu", "sutu", "haserretu"]},
  {"id": "1-149", "hitza": "garratz", "sinonimoak": ["gogor"]},
  {"id": "1-150", "hitza": "zartako", "sinonimoak": ["kolpe", "kaska"]},
  {"id": "1-151", "hitza": "jolasti", "sinonimoak": ["jostakin", "jostalari"]},
  {"id": "1-152", "hitza": "uzki", "sinonimoak": ["ipurtzulo"]},
  {"id": "1-153", "hitza": "otsail", "sinonimoak": ["zezeil"]},
  {"id": "1-154", "hitza": "mugarri", "sinonimoak": ["zedarri"]},
  {"id": "1-155", "hitza": "bozka", "sinonimoak": ["botazio", "bozketa", "hauteskunde"]},
  {"id": "1-156", "hitza": "findu", "sinonimoak": ["leundu", "hobetu"]},
  {"id": "1-157", "hitza": "ikusgaitasun", "sinonimoak": ["agerikotasun", "ikusgarritasun"]},
  {"id": "1-158", "hitza": "sariztatu", "sinonimoak": ["saritu"]},
  {"id": "1-159", "hitza": "biritxi", "sinonimoak": ["biki"]},
  {"id": "1-160", "hitza": "xerkatu", "sinonimoak": ["bilatu"]},

  /* BLOQUE 4 (161-180) */
  {"id": "1-161", "hitza": "behar-beharrezko", "sinonimoak": ["baitezpadako", "ezinbesteko"]},
  {"id": "1-162", "hitza": "alimaleko", "sinonimoak": ["ikaragarrizko", "izugarrizko"]},
  {"id": "1-163", "hitza": "karrika", "sinonimoak": ["kale"]},
  {"id": "1-164", "hitza": "hizketaldi", "sinonimoak": ["elkarrizketa", "solasaldi", "konbertsazio"]},
  {"id": "1-165", "hitza": "izapide", "sinonimoak": ["tramite", "gestio"]},
  {"id": "1-166", "hitza": "urri", "sinonimoak": ["bakan", "gutxi"]},
  {"id": "1-167", "hitza": "helegite", "sinonimoak": ["apelazio"]},
  {"id": "1-168", "hitza": "ustiatu", "sinonimoak": ["esplotatu"]},
  {"id": "1-169", "hitza": "itsasadar", "sinonimoak": ["errio"]},
  {"id": "1-170", "hitza": "deigarri", "sinonimoak": ["nabarmen"]},
  {"id": "1-171", "hitza": "gizalege", "sinonimoak": ["jokaera", "ibilera"]},
  {"id": "1-172", "hitza": "zeresan", "sinonimoak": ["esamesa", "zurrumurru", "esateko"]},
  {"id": "1-173", "hitza": "zinez", "sinonimoak": ["benetan", "egiatan", "egiaz"]},
  {"id": "1-174", "hitza": "zio", "sinonimoak": ["arrazoi", "zergati"]},
  {"id": "1-175", "hitza": "zital", "sinonimoak": ["gaizto", "ziztrin"]},
  {"id": "1-176", "hitza": "pilare", "sinonimoak": ["zutabe", "habe", "harroin"]},
  {"id": "1-177", "hitza": "pairaezin", "sinonimoak": ["jasanezin", "eramanezin"]},
  {"id": "1-178", "hitza": "ohoin", "sinonimoak": ["ebasle", "lapur"]},
  {"id": "1-179", "hitza": "odolbildu", "sinonimoak": ["odolbatu", "beltzune", "ubeldura"]},
  {"id": "1-180", "hitza": "nahigabe", "sinonimoak": ["atsekabe", "bihozmin", "samin"]},

  /* BLOQUE 5 (181-200) */
  {"id": "1-181", "hitza": "lotsati", "sinonimoak": ["herabe", "uzkur"]},
  {"id": "1-182", "hitza": "labainka", "sinonimoak": ["irristaka"]},
  {"id": "1-183", "hitza": "erkatu", "sinonimoak": ["alderatu", "parekatu", "konparatu"]},
  {"id": "1-184", "hitza": "kirri", "sinonimoak": ["hozki", "hozkamin", "tirri"]},
  {"id": "1-185", "hitza": "karan", "sinonimoak": ["eder"]},
  {"id": "1-186", "hitza": "kaiku", "sinonimoak": ["kirten", "lerdo", "kokolo"]},
  {"id": "1-187", "hitza": "jadetsi", "sinonimoak": ["lortu", "erdietsi"]},
  {"id": "1-188", "hitza": "isiotu", "sinonimoak": ["irazeki", "piztu"]},
  {"id": "1-189", "hitza": "iseka", "sinonimoak": ["burla", "trufa", "ihakin"]},
  {"id": "1-190", "hitza": "ildo", "sinonimoak": ["bide", "hari"]},
  {"id": "1-191", "hitza": "hormatu", "sinonimoak": ["izoztu", "jelatu", "leitu"]},
  {"id": "1-192", "hitza": "gomuta", "sinonimoak": ["oroitzapen", "gogorapen", "oroipen"]},
  {"id": "1-193", "hitza": "geriza", "sinonimoak": ["babesa"]},
  {"id": "1-194", "hitza": "ezkila", "sinonimoak": ["kanpaia"]},
  {"id": "1-195", "hitza": "etekin", "sinonimoak": ["mozkin", "hobari"]},
  {"id": "1-196", "hitza": "estakuru", "sinonimoak": ["aitzakia", "apuko"]},
  {"id": "1-197", "hitza": "ereti", "sinonimoak": ["une", "momentu", "lipar", "istant"]},
  {"id": "1-198", "hitza": "arestian", "sinonimoak": ["lehentxeago", "oraintsu", "oixtion"]},
  {"id": "1-199", "hitza": "aratz", "sinonimoak": ["garbi", "garden"]},
  {"id": "1-200", "hitza": "antxeta", "sinonimoak": ["kaio"]}
];
