import { WordData } from './types';

export const LEVEL_4_PART_1: WordData[] = [
  {"id": "4-1", "hitza": "oztopo", "sinonimoak": ["eragozpen", "traba", "zoztor"]},
  {"id": "4-2", "hitza": "pagotxa", "sinonimoak": ["mauka", "mantxunga", "txoko"]},
  {"id": "4-3", "hitza": "pairagarri", "sinonimoak": ["jasangarri", "onargarri", "eramangarri"]},
  {"id": "4-4", "hitza": "pairu", "sinonimoak": ["egonarri", "eroapen", "pairamen"]},
  {"id": "4-5", "hitza": "paku", "sinonimoak": ["paga", "soldata", "ordainsari"]},
  {"id": "4-6", "hitza": "panpina", "sinonimoak": ["andrakila"]},
  {"id": "4-7", "hitza": "panpox", "sinonimoak": ["polit", "eder", "pinpirin"]},
  {"id": "4-8", "hitza": "papaita", "sinonimoak": ["asmakizun", "igarkizun"]},
  {"id": "4-9", "hitza": "paraje", "sinonimoak": ["inguru", "leku", "txoko"]},
  {"id": "4-10", "hitza": "paratu", "sinonimoak": ["jarri", "ipini"]},
  {"id": "4-11", "hitza": "parekatu", "sinonimoak": ["erkatu", "alderatu", "konparatu"]},
  {"id": "4-12", "hitza": "pario", "sinonimoak": ["apustu", "postura", "dema"]},
  {"id": "4-13", "hitza": "parizta", "sinonimoak": ["keinu", "imintzio", "jestu"]},
  {"id": "4-14", "hitza": "pasadizo", "sinonimoak": ["istorio", "bitxikeria", "gertakari"]},
  {"id": "4-15", "hitza": "pauso", "sinonimoak": ["urrats", "oinkada"]},
  {"id": "4-16", "hitza": "pegar", "sinonimoak": ["tupina", "txantxil", "suil"]},
  {"id": "4-17", "hitza": "pellokeria", "sinonimoak": ["ergelkeria", "kaikukeria", "kirtenkeria"]},
  {"id": "4-18", "hitza": "pentsakor", "sinonimoak": ["gogoetatsu", "hausnartzaile", "pentsatzaile"]},
  {"id": "4-19", "hitza": "pentzu", "sinonimoak": ["konfiantza", "fidantzia", "pentzuda"]},
  {"id": "4-20", "hitza": "pentzutan", "sinonimoak": ["ardurapean", "pentzudan"]},
  {"id": "4-21", "hitza": "perkatx", "sinonimoak": ["arretatsu", "maratz", "arduratsu"]},
  {"id": "4-22", "hitza": "peskizan", "sinonimoak": ["itxaropenean", "zain", "esperoan"]},
  {"id": "4-23", "hitza": "peskizan", "sinonimoak": ["bila", "zain", "esperoan"]},
  {"id": "4-24", "hitza": "petraldu", "sinonimoak": ["txartu", "usteldu", "zapuztu"]},
  {"id": "4-25", "hitza": "pilpilka", "sinonimoak": ["pilpiraka", "taupaka", "taupadaka"]},
  {"id": "4-26", "hitza": "piltzar", "sinonimoak": ["zarpail", "pilda", "zarpa"]},
  {"id": "4-27", "hitza": "pinpirindu", "sinonimoak": ["apaindu", "dotoretu", "panpinatu"]},
  {"id": "4-28", "hitza": "pinporta", "sinonimoak": ["pikor", "garau", "pikorta"]},
  {"id": "4-29", "hitza": "piper", "sinonimoak": ["sasieskola", "txikar"]},
  {"id": "4-30", "hitza": "piper egin", "sinonimoak": ["sasieskola egin", "txikarra egin", "eskola huts egin"]},
  {"id": "4-31", "hitza": "pisutsu", "sinonimoak": ["astun", "pisudun"]},
  {"id": "4-32", "hitza": "pitinkeria", "sinonimoak": ["huskeria", "txikikeria", "zirtzileria"]},
  {"id": "4-33", "hitza": "pitzadura", "sinonimoak": ["arrakala", "arrail", "artesi"]},
  {"id": "4-34", "hitza": "piura", "sinonimoak": ["itxura", "eite", "taxu"]},
  {"id": "4-35", "hitza": "pizgarri", "sinonimoak": ["eragingarri", "bizigarri", "akuilu"]},
  {"id": "4-36", "hitza": "piztia", "sinonimoak": ["basapiztia", "patari", "ihizi"]},
  {"id": "4-37", "hitza": "piztu", "sinonimoak": ["isiotu", "irazeki", "izeki"]},
  {"id": "4-38", "hitza": "ponitu", "sinonimoak": ["ordaindu", "pagatu", "konpondu"]},
  {"id": "4-39", "hitza": "pozgabetu", "sinonimoak": ["nahigabetu", "atsekabetu", "goibeldu", "histu"]},
  {"id": "4-40", "hitza": "praka", "sinonimoak": ["galtza"]},
  {"id": "4-41", "hitza": "prefosta", "sinonimoak": ["jakina", "ez horixe"]},
  {"id": "4-42", "hitza": "prezio", "sinonimoak": ["salneurri"]},
  {"id": "4-43", "hitza": "programa", "sinonimoak": ["egitarau"]},
  {"id": "4-44", "hitza": "progu", "sinonimoak": ["dolu", "luto"]},
  {"id": "4-45", "hitza": "prometatu", "sinonimoak": ["agindu", "hitzeman", "promestu"]},
  {"id": "4-46", "hitza": "pulunpatu", "sinonimoak": ["murgildu", "sartu", "harrapatu"]},
  {"id": "4-47", "hitza": "purrusta", "sinonimoak": ["marmar", "marmario", "sarramuska"]},
  {"id": "4-48", "hitza": "pusketa", "sinonimoak": ["zati", "puska", "tato"]},
  {"id": "4-49", "hitza": "putzu", "sinonimoak": ["osin", "zulo", "istil"]},
  {"id": "4-50", "hitza": "puztu", "sinonimoak": ["harropuztu", "hanpatu", "harrotu"]},
  {"id": "4-51", "hitza": "sabai", "sinonimoak": ["mandio", "lastategi", "belartegi"]},
  {"id": "4-52", "hitza": "sabelandi", "sinonimoak": ["tripontzi", "jatun", "sabelkoi"]},
  {"id": "4-53", "hitza": "sabelgorri", "sinonimoak": ["basati", "anker", "bihozgabe"]},
  {"id": "4-54", "hitza": "sagarno", "sinonimoak": ["sagardo"]},
  {"id": "4-55", "hitza": "sagarroi", "sinonimoak": ["triku", "kirikino"]},
  {"id": "4-56", "hitza": "saihesbide", "sinonimoak": ["desbideratze"]},
  {"id": "4-57", "hitza": "saihests", "sinonimoak": ["alderdi", "alde", "puntu"]},
  {"id": "4-58", "hitza": "sailkatu", "sinonimoak": ["ordenatu", "antolatu", "apailatu"]},
  {"id": "4-59", "hitza": "saio", "sinonimoak": ["ahalegin", "ekinaldi", "saialdi"]},
  {"id": "4-60", "hitza": "sakela", "sinonimoak": ["patrika", "poltsiko"]},
  {"id": "4-61", "hitza": "salgai", "sinonimoak": ["salkizun", "salmenta", "saltzeko"]},
  {"id": "4-62", "hitza": "saltsa", "sinonimoak": ["nahaspila", "zalaparta", "katramila"]},
  {"id": "4-63", "hitza": "samalda", "sinonimoak": ["mordo", "andana", "pilo"]},
  {"id": "4-64", "hitza": "samurtu", "sinonimoak": ["bigundu", "hunkitu", "leundu"]},
  {"id": "4-65", "hitza": "sarbide", "sinonimoak": ["sarrera", "sartze"]},
  {"id": "4-66", "hitza": "sarealdi", "sinonimoak": ["sarekada"]},
  {"id": "4-67", "hitza": "sari", "sinonimoak": ["ordainsari", "donari", "golardo"]},
  {"id": "4-68", "hitza": "sarraski", "sinonimoak": ["triskantza", "txikizio", "sakaila"]},
  {"id": "4-69", "hitza": "sarritan", "sinonimoak": ["askotan", "maiz", "usu"]},
  {"id": "4-70", "hitza": "sasi", "sinonimoak": ["sastraka", "sasitza", "sastrakadi"]},
  {"id": "4-71", "hitza": "sastako", "sinonimoak": ["labankada", "aiztokada", "sastada"]},
  {"id": "4-72", "hitza": "sastar", "sinonimoak": ["zabor", "zakar", "zarama"]},
  {"id": "4-73", "hitza": "segizio", "sinonimoak": ["jarraipen", "segida", "ondorio"]},
  {"id": "4-74", "hitza": "segur aski", "sinonimoak": ["ziur asko", "ziurrenik", "segurutik"]},
  {"id": "4-75", "hitza": "seinale", "sinonimoak": ["adierazgarri", "froga", "erakusgarri"]},
  {"id": "4-76", "hitza": "semebitxi", "sinonimoak": ["seme ponteko", "seme besoetako"]},
  {"id": "4-77", "hitza": "sen", "sinonimoak": ["izaera", "aiurri", "seta"]},
  {"id": "4-78", "hitza": "sendagaitz", "sinonimoak": ["osagaitz"]},
  {"id": "4-79", "hitza": "sendoro", "sinonimoak": ["tinko", "irmoki", "sendo(ki)"]},
  {"id": "4-80", "hitza": "senitartekorik", "sinonimoak": ["ahaide", "familiako"]},
  {"id": "4-81", "hitza": "senperrenak ikusi", "sinonimoak": ["gorriak ikusi", "senperrak ikusi", "beltzak ikusi"]},
  {"id": "4-82", "hitza": "senteria", "sinonimoak": ["ongizate"]},
  {"id": "4-83", "hitza": "sentiberatasun", "sinonimoak": ["sentikortasun", "minberatasun", "gaitzikortasun"]},
  {"id": "4-84", "hitza": "serioski", "sinonimoak": ["benetan", "egiatan", "zinez"]},
  {"id": "4-85", "hitza": "setatu", "sinonimoak": ["tematu", "hisiatu", "gogortu"]},
  {"id": "4-86", "hitza": "sigi-sagan", "sinonimoak": ["esemeseka", "zeharka-meharka"]},
  {"id": "4-87", "hitza": "siku", "sinonimoak": ["ziplo", "zerraldo"]},
  {"id": "4-88", "hitza": "simaur", "sinonimoak": ["ongarri", "gorotz", "sats"]},
  {"id": "4-89", "hitza": "sineste", "sinonimoak": ["sinesmen", "sineskera", "ideia"]},
  {"id": "4-90", "hitza": "sinkusa", "sinonimoak": ["aitzakia", "estakuru", "desenkusa"]},
  {"id": "4-91", "hitza": "sirats", "sinonimoak": ["atsegin", "plazer", "gustu"]},
  {"id": "4-92", "hitza": "soberako", "sinonimoak": ["gehiegizko", "neurriz gaineko", "demaseko"]},
  {"id": "4-93", "hitza": "soilketa", "sinonimoak": ["mozketa", "ebaketa", "botatze"]},
  {"id": "4-94", "hitza": "soingain", "sinonimoak": ["bizkar", "lepo", "sorbalda"]},
  {"id": "4-95", "hitza": "solastatu", "sinonimoak": ["mintzatu", "elekatu", "mintzo"]},
  {"id": "4-96", "hitza": "soluzio", "sinonimoak": ["konponbide", "irtenbide", "aterabide"]},
  {"id": "4-97", "hitza": "sorrera", "sinonimoak": ["hastapen", "jatorri", "iturburu"]},
  {"id": "4-98", "hitza": "suertatu", "sinonimoak": ["halabeharrez"]},
  {"id": "4-99", "hitza": "sumatu", "sinonimoak": ["igarri", "nabaritu", "antzeman"]},
  {"id": "4-100", "hitza": "tai", "sinonimoak": ["eten", "geldialdi", "etenaldi"]}
];