
import { WordData } from './types';

export const LEVEL_1_PART_1: WordData[] = [
  /* BLOQUE 1 (1-20) */
  {"id": "1-1", "hitza": "antzeman", "sinonimoak": ["igarri", "nabaritu", "sumatu", "konturatu", "ohartu"]},
  {"id": "1-2", "hitza": "izutu", "sinonimoak": ["beldurtu", "ikaratu", "kikildu", "oilotu", "koldartu"]},
  {"id": "1-3", "hitza": "hizki", "sinonimoak": ["letra"]},
  {"id": "1-4", "hitza": "ulergaitz", "sinonimoak": ["ulertezin", "adiezin", "adigaitz"]},
  {"id": "1-5", "hitza": "suspertu", "sinonimoak": ["indarberritu"]},
  {"id": "1-6", "hitza": "igorri", "sinonimoak": ["bidali"]},
  {"id": "1-7", "hitza": "zeken", "sinonimoak": ["esku-labur", "zikoitz", "eskulabur"]},
  {"id": "1-8", "hitza": "jakiteko grina", "sinonimoak": ["jakin-min", "jakingura", "jakin-gose", "jakin-nahi"]},
  {"id": "1-9", "hitza": "are gehiago", "sinonimoak": ["areago"]},
  {"id": "1-10", "hitza": "leize", "sinonimoak": ["kobazulo", "haitzulo"]},
  {"id": "1-11", "hitza": "eremu", "sinonimoak": ["alor", "arlo", "esparru", "sail"]},
  {"id": "1-12", "hitza": "hondar", "sinonimoak": ["harea", "hondakin"]},
  {"id": "1-13", "hitza": "gauzatu", "sinonimoak": ["burutu"]},
  {"id": "1-14", "hitza": "esanahi", "sinonimoak": ["esangura", "adiera", "esankizun"]},
  {"id": "1-15", "hitza": "lapurtu", "sinonimoak": ["ostu", "ebatsi"]},
  {"id": "1-16", "hitza": "ahaztu", "sinonimoak": ["ahantzi"]},
  {"id": "1-17", "hitza": "aditzera eman", "sinonimoak": ["jakinarazi", "ezagutarazi", "adierazi"]},
  {"id": "1-18", "hitza": "bestela", "sinonimoak": ["osterantzean", "gainerakoan"]},
  {"id": "1-19", "hitza": "nagusitasun", "sinonimoak": ["gailentasun", "gehiagotasun"]},
  {"id": "1-20", "hitza": "oinatz", "sinonimoak": ["arrasto", "aztarna"]},

  /* BLOQUE 2 (21-40) */
  {"id": "1-21", "hitza": "aztarna", "sinonimoak": ["arrasto", "oinatz"]},
  {"id": "1-22", "hitza": "lohitu", "sinonimoak": ["zikindu", "likistu", "txerritu", "mantxatu"]},
  {"id": "1-23", "hitza": "jazo", "sinonimoak": ["gertatu"]},
  {"id": "1-24", "hitza": "iskanbila", "sinonimoak": ["astrapala", "zalaparta", "zarraparra"]},
  {"id": "1-25", "hitza": "ikuzi", "sinonimoak": ["garbitu", "txukundu", "xahutu", "araztu"]},
  {"id": "1-26", "hitza": "nabarmendu", "sinonimoak": ["nagusitu", "gailendu", "gailurtu"]},
  {"id": "1-27", "hitza": "gizendu", "sinonimoak": ["loditu", "guritu", "marduldu", "galantu", "mardotu"]},
  {"id": "1-28", "hitza": "sustraitu", "sinonimoak": ["errotu", "erroak bota"]},
  {"id": "1-29", "hitza": "martxan jarri", "sinonimoak": ["abiarazi", "abian jarri"]},
  {"id": "1-30", "hitza": "edozenbat", "sinonimoak": ["nahi beste", "nahi adina", "gura adina"]},
  {"id": "1-31", "hitza": "miresmen", "sinonimoak": ["gurtza"]},
  {"id": "1-32", "hitza": "entzun", "sinonimoak": ["aditu"]},
  {"id": "1-33", "hitza": "ulertu", "sinonimoak": ["aditu", "jabetu"]},
  {"id": "1-34", "hitza": "ezelango", "sinonimoak": ["inola"]},
  {"id": "1-35", "hitza": "zaratatsua", "sinonimoak": ["arramatsu", "astrapalatsu"]},
  {"id": "1-36", "hitza": "oztopoa", "sinonimoak": ["destorbu", "eragozpen", "traba"]},
  {"id": "1-37", "hitza": "munstro", "sinonimoak": ["piztia"]},
  {"id": "1-38", "hitza": "heldu", "sinonimoak": ["eutsi", "oratu", "lotu"]},
  {"id": "1-39", "hitza": "iritsi", "sinonimoak": ["ailegatu", "erdutu", "heldu"]},
  {"id": "1-40", "hitza": "hurko", "sinonimoak": ["hurbileko", "aldeko"]},

  /* BLOQUE 3 (41-60) */
  {"id": "1-41", "hitza": "hurko", "sinonimoak": ["hurbileko", "aldeko"]},
  {"id": "1-42", "hitza": "kartela", "sinonimoak": ["afixa", "idazkun"]},
  {"id": "1-43", "hitza": "arerioa", "sinonimoak": ["etsai", "aurkari", "izterbegi"]},
  {"id": "1-44", "hitza": "suertatu", "sinonimoak": ["gertatu", "jazo"]},
  {"id": "1-45", "hitza": "hurbildu", "sinonimoak": ["hurreratu", "gerturatu"]},
  {"id": "1-46", "hitza": "ekidin", "sinonimoak": ["saihestu"]},
  {"id": "1-47", "hitza": "atzaparra", "sinonimoak": ["erpe", "atzamar"]},
  {"id": "1-48", "hitza": "seko", "sinonimoak": ["guztiz", "zeharo", "total", "erabat"]},
  {"id": "1-49", "hitza": "hanka", "sinonimoak": ["zango", "berna", "izter"]},
  {"id": "1-50", "hitza": "berna", "sinonimoak": ["zangosagar", "aztal", "zangar"]},
  {"id": "1-51", "hitza": "jin", "sinonimoak": ["etorri"]},
  {"id": "1-52", "hitza": "irla", "sinonimoak": ["uharte"]},
  {"id": "1-53", "hitza": "oroitu", "sinonimoak": ["gogoratu", "gomutatu", "gogoan izan"]},
  {"id": "1-54", "hitza": "izaera", "sinonimoak": ["aiurri", "nortasun", "seta"]},
  {"id": "1-55", "hitza": "gaitzetsi", "sinonimoak": ["ezetsi", "hastandu"]},
  {"id": "1-56", "hitza": "ortu", "sinonimoak": ["baratze"]},
  {"id": "1-57", "hitza": "eltze", "sinonimoak": ["lapiko", "tupina"]},
  {"id": "1-58", "hitza": "kapela", "sinonimoak": ["txano"]},
  {"id": "1-59", "hitza": "mediku", "sinonimoak": ["sendagile", "osagile", "osatzaile"]},
  {"id": "1-60", "hitza": "oski", "sinonimoak": ["zapata"]},

  /* BLOQUE 4 (61-80) */
  {"id": "1-61", "hitza": "goraintzi", "sinonimoak": ["eskumuin"]},
  {"id": "1-62", "hitza": "zama", "sinonimoak": ["karga", "haxe"]},
  {"id": "1-63", "hitza": "eserleku", "sinonimoak": ["jarleku", "jesarleku", "esertoki"]},
  {"id": "1-64", "hitza": "arraro", "sinonimoak": ["bitxi", "arrotz"]},
  {"id": "1-65", "hitza": "ezezaguna", "sinonimoak": ["arrotz"]},
  {"id": "1-66", "hitza": "familia", "sinonimoak": ["sendi", "senitarte"]},
  {"id": "1-67", "hitza": "ezkutatu", "sinonimoak": ["ostendu"]},
  {"id": "1-68", "hitza": "hondatu", "sinonimoak": ["suntsitu", "erraustu", "txikitu"]},
  {"id": "1-69", "hitza": "beti", "sinonimoak": ["betiere", "aldiro", "une oro", "aldi oro"]},
  {"id": "1-70", "hitza": "salto egin", "sinonimoak": ["jauzi egin", "saltatu"]},
  {"id": "1-71", "hitza": "begiratu", "sinonimoak": ["behatu", "so egin"]},
  {"id": "1-72", "hitza": "indarkeria", "sinonimoak": ["bortxakeria", "gogorkeria", "biolentzia"]},
  {"id": "1-73", "hitza": "bide batez", "sinonimoak": ["bidenabar", "bidez"]},
  {"id": "1-74", "hitza": "hozbero", "sinonimoak": ["tenperatura"]},
  {"id": "1-75", "hitza": "sargori", "sinonimoak": ["sapa", "lanbero"]},
  {"id": "1-76", "hitza": "umel", "sinonimoak": ["heze", "ezko", "busti"]},
  {"id": "1-77", "hitza": "erauzi", "sinonimoak": ["kendu", "idoki"]},
  {"id": "1-78", "hitza": "oihartzun", "sinonimoak": ["durundi"]},
  {"id": "1-79", "hitza": "galbideratu", "sinonimoak": ["perbertitu", "okertu"]},
  {"id": "1-80", "hitza": "gupida", "sinonimoak": ["erruki", "urriki"]},

  /* BLOQUE 5 (81-100) */
  {"id": "1-81", "hitza": "inguruabar", "sinonimoak": ["egoera", "zertzelada", "kondizio"]},
  {"id": "1-82", "hitza": "lotsagabe", "sinonimoak": ["lotsabako", "lotsagaldu", "ahalkegabe"]},
  {"id": "1-83", "hitza": "iragarri", "sinonimoak": ["komunikatu", "jakinarazi"]},
  {"id": "1-84", "hitza": "emanaldi", "sinonimoak": ["emankizun", "saio", "emisio"]},
  {"id": "1-85", "hitza": "esamesa", "sinonimoak": ["zurrumurru", "erran-merran", "elepide"]},
  {"id": "1-86", "hitza": "belaunaldi", "sinonimoak": ["gizaldi"]},
  {"id": "1-87", "hitza": "argitaraldi", "sinonimoak": ["argitalpen", "edizio"]},
  {"id": "1-88", "hitza": "gorespen", "sinonimoak": ["goraipamen", "gorazarre", "laudorio", "laudamen"]},
  {"id": "1-89", "hitza": "biziraute", "sinonimoak": ["biziraupen"]},
  {"id": "1-90", "hitza": "kaskartu", "sinonimoak": ["txartu", "okerragotu", "gaizkoatu"]},
  {"id": "1-91", "hitza": "ezkontide", "sinonimoak": ["ezkonlagun", "bizikide", "bizilagun"]},
  {"id": "1-92", "hitza": "deitoratu", "sinonimoak": ["auhendatu", "adiakatu", "tamaldu", "penatu"]},
  {"id": "1-93", "hitza": "berau", "sinonimoak": ["hauxe", "hau bera"]},
  {"id": "1-94", "hitza": "sastakatu", "sinonimoak": ["sastatu", "aiztoa sartu"]},
  {"id": "1-95", "hitza": "emagaldu", "sinonimoak": ["ematxar", "urdanga", "maritzar", "julis", "bordion"]},
  {"id": "1-96", "hitza": "zoroetxe", "sinonimoak": ["eroetxe", "erotegi"]},
  {"id": "1-97", "hitza": "biziraupen", "sinonimoak": ["biziraute"]},
  {"id": "1-98", "hitza": "burrunba", "sinonimoak": ["danbada", "dunbots", "danbateko"]},
  {"id": "1-99", "hitza": "jalgi", "sinonimoak": ["atera", "ilki"]},
  {"id": "1-100", "hitza": "iaio", "sinonimoak": ["trebe", "abil", "artetsu"]}
];
