import { WordData } from './types';

export const LEVEL_4_PART_4: WordData[] = [
  {"id": "4-301", "hitza": "zalapartaka", "sinonimoak": ["arrapaladan", "presaka", "lasterka", "antxintxika"]},
  {"id": "4-302", "hitza": "zaldakatu", "sinonimoak": ["lokaztu", "lohiztatu", "idoiztatu"]},
  {"id": "4-303", "hitza": "zaletu", "sinonimoak": ["grinatu", "guratu", "nahitu"]},
  {"id": "4-304", "hitza": "zalukeria", "sinonimoak": ["maltzurkeria", "azerikeria", "faltsukeria"]},
  {"id": "4-305", "hitza": "zamatu", "sinonimoak": ["sortatu", "kargatu"]},
  {"id": "4-306", "hitza": "zanbrotu", "sinonimoak": ["azala urratu", "azala arraspatu"]},
  {"id": "4-307", "hitza": "zango", "sinonimoak": ["hanka", "berna"]},
  {"id": "4-308", "hitza": "zankuts", "sinonimoak": ["oinuts(ik)", "ortozik", "hanka hutsik"]},
  {"id": "4-309", "hitza": "zanpaketa", "sinonimoak": ["zapalkuntza", "errepresio", "zapalketa"]},
  {"id": "4-310", "hitza": "zaparrada", "sinonimoak": ["indriska", "euri-jasa", "zaldizko"]},
  {"id": "4-311", "hitza": "zaputz", "sinonimoak": ["muzin", "muker", "betizu"]},
  {"id": "4-312", "hitza": "zaramarra", "sinonimoak": ["azantz", "zalaparta", "iskanbila"]},
  {"id": "4-313", "hitza": "zarbaildu", "sinonimoak": ["narriatu", "izorratu", "hondatu"]},
  {"id": "4-314", "hitza": "zarrastelkeria", "sinonimoak": ["xahubide", "eralgiketa", "xahutze"]},
  {"id": "4-315", "hitza": "zatarreria", "sinonimoak": ["zakarreria", "zaborreria", "sastar"]},
  {"id": "4-316", "hitza": "zazpiki", "sinonimoak": ["pairugabe", "pazientzia gutxiko"]},
  {"id": "4-317", "hitza": "zedarritu", "sinonimoak": ["finkatu", "xedatu", "mugatu"]},
  {"id": "4-318", "hitza": "zegan", "sinonimoak": ["zenbatean"]},
  {"id": "4-319", "hitza": "zeharka-meharka", "sinonimoak": ["sigi-sagan", "itzulinguruka", "zeharbidez"]},
  {"id": "4-320", "hitza": "zeharretara", "sinonimoak": ["saiheska", "soslaiz", "alboz"]},
  {"id": "4-321", "hitza": "zehatu", "sinonimoak": ["zigortu", "punitu", "gaztigatu"]},
  {"id": "4-322", "hitza": "zekendu", "sinonimoak": ["zikoiztu", "diruzaletu", "xuhurtu"]},
  {"id": "4-323", "hitza": "zelai", "sinonimoak": ["landa", "larre", "belardi"]},
  {"id": "4-324", "hitza": "zelanbait", "sinonimoak": ["nolabait", "nola edo hala", "nolerebait"]},
  {"id": "4-325", "hitza": "zemaitu", "sinonimoak": ["mehatxatu", "larderiatu", "estutu"]},
  {"id": "4-326", "hitza": "zendu", "sinonimoak": ["hildako", "hil", "defuntu"]},
  {"id": "4-327", "hitza": "zentsura", "sinonimoak": ["traba", "oztopo", "eragozpen"]},
  {"id": "4-328", "hitza": "zentzubekeria", "sinonimoak": ["burugabekeria", "erokeria", "burtzorakeria"]},
  {"id": "4-329", "hitza": "zerbeldu", "sinonimoak": ["hotzildu", "epeldu"]},
  {"id": "4-330", "hitza": "zeregin", "sinonimoak": ["eginkizun", "funtzio", "eginbehar"]},
  {"id": "4-331", "hitza": "zergati", "sinonimoak": ["arrazoi", "kari", "zio"]},
  {"id": "4-332", "hitza": "zerikusi", "sinonimoak": ["harreman", "lotura", "erlazio"]},
  {"id": "4-333", "hitza": "zerraldo", "sinonimoak": ["siku", "ziplo", "plaust"]},
  {"id": "4-334", "hitza": "zertzelada", "sinonimoak": ["zehaztasun", "xehetasun", "xehadura"]},
  {"id": "4-335", "hitza": "zeruertz", "sinonimoak": ["zerumuga", "ostertz", "hodeiertz"]},
  {"id": "4-336", "hitza": "zibilizatu", "sinonimoak": ["hezi", "jendetu"]},
  {"id": "4-337", "hitza": "ziho", "sinonimoak": ["gantz", "urin", "bilgor"]},
  {"id": "4-338", "hitza": "zikiratu", "sinonimoak": ["irendu", "irantzi"]},
  {"id": "4-339", "hitza": "zildai", "sinonimoak": ["muturreko", "mozal"]},
  {"id": "4-340", "hitza": "zilegitu", "sinonimoak": ["baimendu", "onartu", "onetsi"]},
  {"id": "4-341", "hitza": "zimarku", "sinonimoak": ["iruzur", "amarru", "jukutria"]},
  {"id": "4-342", "hitza": "zimiko", "sinonimoak": ["imurtxi", "atximur", "txatxamur"]},
  {"id": "4-343", "hitza": "zimurkeria", "sinonimoak": ["diruzalekeria", "zekenkeria", "zuhurkeria"]},
  {"id": "4-344", "hitza": "zin-zinez", "sinonimoak": ["bene-benetan", "zinez eta minez", "egia-egiatan"]},
  {"id": "4-345", "hitza": "zindo", "sinonimoak": ["langile", "lanzale", "saiatu", "osasuntsu"]},
  {"id": "4-346", "hitza": "zinemaratu", "sinonimoak": ["pantailaratu", "proiektatu", "filmarazi"]},
  {"id": "4-347", "hitza": "zintzotasun", "sinonimoak": ["onestasun", "prestutasun", "ondradutasun"]},
  {"id": "4-348", "hitza": "zintzurkoi", "sinonimoak": ["jatun", "tripontzi", "salo"]},
  {"id": "4-349", "hitza": "zintzurleun", "sinonimoak": ["ahozuri", "mokofin"]},
  {"id": "4-350", "hitza": "zira", "sinonimoak": ["euri-kapusai", "anorak"]},
  {"id": "4-351", "hitza": "zirikatu", "sinonimoak": ["xaxatu", "ahakatu", "probokatu"]},
  {"id": "4-352", "hitza": "zirko", "sinonimoak": ["etxarte", "kalezulo", "sohorna"]},
  {"id": "4-353", "hitza": "zirpildu", "sinonimoak": ["listu", "pirukatu"]},
  {"id": "4-354", "hitza": "zirrara", "sinonimoak": ["hunkipen", "sentsazio", "zarrasta"]},
  {"id": "4-355", "hitza": "zirtzileria", "sinonimoak": ["purtzilkeria", "zizki-mizki", "huskeria"]},
  {"id": "4-356", "hitza": "ziurrenik", "sinonimoak": ["ziur aski", "asko", "segurutik", "segur aski"]},
  {"id": "4-357", "hitza": "zizini", "sinonimoak": ["asmo", "xede", "uste", "intentzio"]},
  {"id": "4-358", "hitza": "ziztrin", "sinonimoak": ["txatxar", "hutsal", "purtzil"]},
  {"id": "4-359", "hitza": "zokoratu", "sinonimoak": ["bazterreratu", "alboratu", "baztertu"]},
  {"id": "4-360", "hitza": "zoli", "sinonimoak": ["prestu", "erne", "bizkor", "ozen"]},
  {"id": "4-361", "hitza": "zoratu", "sinonimoak": ["erotu", "txoratu", "burutik egin"]},
  {"id": "4-362", "hitza": "zoritxarreko", "sinonimoak": ["zorigabeko", "zorigaiztoko", "zorigaitzezko", "dohakabeko"]},
  {"id": "4-363", "hitza": "zorritsu", "sinonimoak": ["zikin", "koipezto", "zorrizto"]},
  {"id": "4-364", "hitza": "zorroztasun", "sinonimoak": ["gogortasun", "zurruntasun", "irmotasun"]},
  {"id": "4-365", "hitza": "zozotu", "sinonimoak": ["txepeldu", "totolotu", "memelotu"]},
  {"id": "4-366", "hitza": "zubioto", "sinonimoak": ["zaldain", "pasagune", "pasabide"]},
  {"id": "4-367", "hitza": "zuhail", "sinonimoak": ["hits", "zurbil", "beluri"]},
  {"id": "4-368", "hitza": "zuhaitzi", "sinonimoak": ["arboladi", "baso", "oihan"]},
  {"id": "4-369", "hitza": "zulatze", "sinonimoak": ["indusketa", "hondaketa", "prospekzio"]},
  {"id": "4-370", "hitza": "zurikeria", "sinonimoak": ["losintxa", "lausengu", "balaku", "laudorio"]},
  {"id": "4-371", "hitza": "zurmindu", "sinonimoak": ["sorgortu", "hozmindu", "malgortu"]},
  {"id": "4-372", "hitza": "zurtu", "sinonimoak": ["harritu", "txunditu", "espantatu"]},
  {"id": "4-373", "hitza": "zutundu", "sinonimoak": ["zutitu", "altxatu", "jaiki"]},
  {"id": "4-374", "hitza": "zuzen", "sinonimoak": ["artez"]},
  {"id": "4-375", "hitza": "zuztartu", "sinonimoak": ["sustraitu", "errotu", "bertakotu"]}
];