import { WordData } from './types';

export const LEVEL_4_PART_3: WordData[] = [
   {"id": "4-201", "hitza": "urburu", "sinonimoak": ["iturburu", "iturbegi", "iturri"]},
  {"id": "4-202", "hitza": "urdail", "sinonimoak": ["sabel"]},
  {"id": "4-203", "hitza": "urdekeria", "sinonimoak": ["txerrikeria", "zikinkeria", "zerrikeria"]},
  {"id": "4-204", "hitza": "urdindu", "sinonimoak": ["zuritu"]},
  {"id": "4-205", "hitza": "urduritasun", "sinonimoak": ["artegatasun", "larritasun", "egonezin"]},
  {"id": "4-206", "hitza": "uretaratu", "sinonimoak": ["pulunpatu", "urperatu", "murgildu"]},
  {"id": "4-207", "hitza": "urgazle", "sinonimoak": ["laguntzaile", "kolaboratzaile"]},
  {"id": "4-208", "hitza": "urgoi", "sinonimoak": ["lotsati", "herabeti", "uzkur"]},
  {"id": "4-209", "hitza": "urkuldu", "sinonimoak": ["aletu", "bihitu", "garautu"]},
  {"id": "4-210", "hitza": "urmael", "sinonimoak": ["urlo", "putzu", "istil"]},
  {"id": "4-211", "hitza": "urperatu", "sinonimoak": ["hondoratu", "pulunpatu", "murgilarazi"]},
  {"id": "4-212", "hitza": "urradura", "sinonimoak": ["ebaki", "zauri", "arrakala"]},
  {"id": "4-213", "hitza": "urratu", "sinonimoak": ["hautsi", "puskatu"]},
  {"id": "4-214", "hitza": "urregorri", "sinonimoak": ["urre"]},
  {"id": "4-215", "hitza": "urrendu", "sinonimoak": ["amaitu", "bukatu"]},
  {"id": "4-216", "hitza": "urri", "sinonimoak": ["gutxi", "eskas", "murritz"]},
  {"id": "4-217", "hitza": "urrikaldu", "sinonimoak": ["gupidatu", "errukitu", "kupitu"]},
  {"id": "4-218", "hitza": "urripen", "sinonimoak": ["murrizketa", "lerma", "jaitsiera"]},
  {"id": "4-219", "hitza": "urrundu", "sinonimoak": ["aldendu", "urrutiratu", "lekutu"]},
  {"id": "4-220", "hitza": "urtabe", "sinonimoak": ["uztaldi", "uztaro", "urtebete"]},
  {"id": "4-221", "hitza": "urtatu", "sinonimoak": ["urtetsu", "zahar", "aspaldiko"]},
  {"id": "4-222", "hitza": "urtebetetze", "sinonimoak": ["urtemuga", "egun", "urteurren"]},
  {"id": "4-223", "hitza": "urtxintxa", "sinonimoak": ["katagorri"]},
  {"id": "4-224", "hitza": "urtze-garai", "sinonimoak": ["urtzaldi", "urtzaro"]},
  {"id": "4-225", "hitza": "usadio", "sinonimoak": ["ohitura", "ekandu", "aztura"]},
  {"id": "4-226", "hitza": "usin", "sinonimoak": ["doministiku"]},
  {"id": "4-227", "hitza": "usnatu", "sinonimoak": ["sumatu", "aditu", "usaindu"]},
  {"id": "4-228", "hitza": "uspeldura", "sinonimoak": ["beltzune", "ubeldura", "odolbatu"]},
  {"id": "4-229", "hitza": "uspelgune", "sinonimoak": ["laioz", "ospel"]},
  {"id": "4-230", "hitza": "ustekabean", "sinonimoak": ["ezustean", "itsumustuan", "tupustean"]},
  {"id": "4-231", "hitza": "usteldu", "sinonimoak": ["galdu", "hondatu", "zapuztu"]},
  {"id": "4-232", "hitza": "ustez", "sinonimoak": ["aburuz", "iritzi", "irudiko(z)"]},
  {"id": "4-233", "hitza": "ustiagarri", "sinonimoak": ["erabilgarri", "baliagarri", "aprobetxagarri"]},
  {"id": "4-234", "hitza": "ustiaketa", "sinonimoak": ["ustiapen", "esplotazio", "ustiatze"]},
  {"id": "4-235", "hitza": "usu", "sinonimoak": ["maiz", "askotan", "sarri"]},
  {"id": "4-236", "hitza": "utikan", "sinonimoak": ["alde", "ospa", "hanka"]},
  {"id": "4-237", "hitza": "uxaldu", "sinonimoak": ["zimeldu", "ihartu", "faundu"]},
  {"id": "4-238", "hitza": "uxatu", "sinonimoak": ["izutu", "ikaratu", "beldurtu"]},
  {"id": "4-239", "hitza": "uxter", "sinonimoak": ["samur", "bigun", "guri"]},
  {"id": "4-240", "hitza": "uxuka-muxuka", "sinonimoak": ["txutxu-mutxuka", "xuxurlaka", "murmurioka"]},
  {"id": "4-241", "hitza": "uzkaili", "sinonimoak": ["irauli"]},
  {"id": "4-242", "hitza": "uzkaldu", "sinonimoak": ["lotu", "estekatu", "josi"]},
  {"id": "4-243", "hitza": "uzkurtu", "sinonimoak": ["koldartu", "ulitu", "kikildu"]},
  {"id": "4-244", "hitza": "uztai", "sinonimoak": ["zirrindola", "zirgilo", "obo"]},
  {"id": "4-245", "hitza": "uztardura", "sinonimoak": ["lotura", "esteka", "lokarri"]},
  {"id": "4-246", "hitza": "uztartu", "sinonimoak": ["antxumatu", "gurutzatu"]},
  {"id": "4-247", "hitza": "xafarratu", "sinonimoak": ["irakuzi", "garbitu", "ikuzi"]},
  {"id": "4-248", "hitza": "xafla", "sinonimoak": ["xerra", "zati", "puska"]},
  {"id": "4-249", "hitza": "xahu", "sinonimoak": ["aratz", "garbi", "lasai"]},
  {"id": "4-250", "hitza": "xahutzaile", "sinonimoak": ["zarrastel", "iriole", "gastatzaile"]},
  {"id": "4-251", "hitza": "xai", "sinonimoak": ["soto", "upategi", "biltegi"]},
  {"id": "4-252", "hitza": "xaki", "sinonimoak": ["marka", "seinale", "ezaugarri"]},
  {"id": "4-253", "hitza": "xalo", "sinonimoak": ["atsegin", "xehe", "apal"]},
  {"id": "4-254", "hitza": "xanfarin", "sinonimoak": ["txoriburu", "nahaba", "kaskarin"]},
  {"id": "4-255", "hitza": "xantxa", "sinonimoak": ["kaiku", "ontzi"]},
  {"id": "4-256", "hitza": "xapoka", "sinonimoak": ["pixkanaka", "apurka", "pitinka"]},
  {"id": "4-257", "hitza": "xaribari", "sinonimoak": ["zalaparta", "azantz", "zarata"]},
  {"id": "4-258", "hitza": "xarma", "sinonimoak": ["lilura", "erakarpen", "xarmadura"]},
  {"id": "4-259", "hitza": "xatar", "sinonimoak": ["pixoihal", "troxa", "haur-oihal"]},
  {"id": "4-260", "hitza": "xauxun", "sinonimoak": ["muturluze", "sarkin", "endreda-makila"]},
  {"id": "4-261", "hitza": "xaxatu", "sinonimoak": ["akuilatu", "zirikatu", "kinatu", "aizkatu"]},
  {"id": "4-262", "hitza": "xedatu", "sinonimoak": ["zehaztu", "adierazi", "finkatu"]},
  {"id": "4-263", "hitza": "xede", "sinonimoak": ["helburu", "asmo", "jomuga"]},
  {"id": "4-264", "hitza": "xehatu", "sinonimoak": ["txikitu", "birrindu", "zatitu"]},
  {"id": "4-265", "hitza": "xehetasun", "sinonimoak": ["zehaztasun", "argibide", "azalpen"]},
  {"id": "4-266", "hitza": "xelebre", "sinonimoak": ["gatzdun", "barregarri", "txistagarri"]},
  {"id": "4-267", "hitza": "xendra", "sinonimoak": ["bidezidor", "bidexka", "basabide"]},
  {"id": "4-268", "hitza": "xerka", "sinonimoak": ["bila"]},
  {"id": "4-269", "hitza": "xerlotsu", "sinonimoak": ["iletsu", "iledun", "bilotsu"]},
  {"id": "4-270", "hitza": "xextra", "sinonimoak": ["sesio", "errieta", "kalapita"]},
  {"id": "4-271", "hitza": "xifrialdi", "sinonimoak": ["estualdi", "larrialdi", "itoaldi"]},
  {"id": "4-272", "hitza": "xikotu", "sinonimoak": ["larrua jo", "txortan egin", "larrutan egin"]},
  {"id": "4-273", "hitza": "xildre", "sinonimoak": ["korapilo", "begizta", "begite"]},
  {"id": "4-274", "hitza": "xilintxa", "sinonimoak": ["zintzarri", "joare", "arran"]},
  {"id": "4-275", "hitza": "ximen", "sinonimoak": ["apain", "garbi", "txukun"]},
  {"id": "4-276", "hitza": "xingilka", "sinonimoak": ["txingoka", "txingoan"]},
  {"id": "4-277", "hitza": "xingola-mingola", "sinonimoak": ["sigi-sagan", "esemeseka", "zeharka-meharka"]},
  {"id": "4-278", "hitza": "xiringatu", "sinonimoak": ["injektatu", "txertatu", "jarri"]},
  {"id": "4-279", "hitza": "xirrika-xarraka", "sinonimoak": ["tipi-tapa", "tirriki-tarraka", "astiro-astiro"]},
  {"id": "4-280", "hitza": "xitxer", "sinonimoak": ["txingor", "kazkabar", "babazuza"]},
  {"id": "4-281", "hitza": "xixkatu", "sinonimoak": ["iruzur egin", "ziria sartu", "irusako egin"]},
  {"id": "4-282", "hitza": "xuhur", "sinonimoak": ["zeken", "esku-labur", "zikoitz", "zuhur"]},
  {"id": "4-283", "hitza": "xukatu", "sinonimoak": ["lehortu", "sikatu"]},
  {"id": "4-284", "hitza": "xume", "sinonimoak": ["xehe", "apal", "lau"]},
  {"id": "4-285", "hitza": "xurgatze", "sinonimoak": ["zurrupatze", "irenste", "hurrupatze"]},
  {"id": "4-286", "hitza": "xuxurla", "sinonimoak": ["marmar", "murmurio", "zurrumurru"]},
  {"id": "4-287", "hitza": "zabaldi", "sinonimoak": ["ordoki", "lautada", "zelaidi"]},
  {"id": "4-288", "hitza": "zabaldu", "sinonimoak": ["hedatu", "barreiatu"]},
  {"id": "4-289", "hitza": "zabalera", "sinonimoak": ["hedadura", "eremu", "esparru"]},
  {"id": "4-290", "hitza": "zabalik", "sinonimoak": ["irekirik"]},
  {"id": "4-291", "hitza": "zabaltza", "sinonimoak": ["teilatu lau"]},
  {"id": "4-292", "hitza": "zabarkeria", "sinonimoak": ["arduragabekeria", "utzikeria", "axolagabekeria"]},
  {"id": "4-293", "hitza": "zabartu", "sinonimoak": ["axolagabetu", "alfertu", "arduragabetu"]},
  {"id": "4-294", "hitza": "zabo", "sinonimoak": ["hantura", "handitu", "handitsu"]},
  {"id": "4-295", "hitza": "zabor", "sinonimoak": ["zakar", "zarama", "hondakin"]},
  {"id": "4-296", "hitza": "zabu", "sinonimoak": ["leria", "kulunka"]},
  {"id": "4-297", "hitza": "zadora", "sinonimoak": ["kuxidade", "nahaspila", "anabasa"]},
  {"id": "4-298", "hitza": "zaflada", "sinonimoak": ["zaplazteko", "masaileko", "belarrondoko"]},
  {"id": "4-299", "hitza": "zaildu", "sinonimoak": ["gogortu", "laztu"]},
  {"id": "4-300", "hitza": "zakil", "sinonimoak": ["kikirrio", "armegain", "buztan", "armagi"]}
];