import { WordData } from './types';

export const LEVEL_3_PART_2: WordData[] = [
  {"id": "3-101", "hitza": "kitzikatu", "sinonimoak": ["berotu"]},
  {"id": "3-102", "hitza": "koadro", "sinonimoak": ["margolan", "pintura", "artelan"]},
  {"id": "3-103", "hitza": "koipetsu", "sinonimoak": ["koipeztu", "ugerdo", "krakatsu"]},
  {"id": "3-104", "hitza": "kokorro", "sinonimoak": ["zakar", "oies", "kaskarro"]},
  {"id": "3-105", "hitza": "kokospe", "sinonimoak": ["girgilo"]},
  {"id": "3-106", "hitza": "komun", "sinonimoak": ["ohiko", "arrunt", "agizko"]},
  {"id": "3-107", "hitza": "koskortu", "sinonimoak": ["hazi", "handitu", "tarrotu"]},
  {"id": "3-108", "hitza": "kraskatu", "sinonimoak": ["pitzatu", "arrakalatu", "arraildu"]},
  {"id": "3-109", "hitza": "kukutu", "sinonimoak": ["estali", "ezkutatu", "ostendu"]},
  {"id": "3-110", "hitza": "kutsadura", "sinonimoak": ["poluzio"]},
  {"id": "3-111", "hitza": "kutsu", "sinonimoak": ["ukitu", "eragin", "azentu"]},
  {"id": "3-112", "hitza": "kuxkuxean", "sinonimoak": ["zokomiran", "ikusmiran", "usainka"]},
  {"id": "3-113", "hitza": "labainkor", "sinonimoak": ["irristakor", "lerrakor", "limurkor"]},
  {"id": "3-114", "hitza": "laborari", "sinonimoak": ["nekazari", "baserritar"]},
  {"id": "3-115", "hitza": "laborri", "sinonimoak": ["ikara", "izu", "beldur"]},
  {"id": "3-116", "hitza": "laga", "sinonimoak": ["utzi", "mailegatu"]},
  {"id": "3-117", "hitza": "lagungarri", "sinonimoak": ["onuragarri", "mesedegarri", "probetxugarri"]},
  {"id": "3-118", "hitza": "laguntzaile", "sinonimoak": ["azafata", "harreragile"]},
  {"id": "3-119", "hitza": "lainotu", "sinonimoak": ["hodeitu", "goibeldu", "ilundu"]},
  {"id": "3-120", "hitza": "laket", "sinonimoak": ["atsegin", "gogoko", "gustuko"]},
  {"id": "3-121", "hitza": "lanabes", "sinonimoak": ["tresna", "erreminta", "langai"]},
  {"id": "3-122", "hitza": "lanaldi", "sinonimoak": ["lansaio", "lanegun", "jardunaldi"]},
  {"id": "3-123", "hitza": "lander", "sinonimoak": ["txiro", "behartsu", "erromes"]},
  {"id": "3-124", "hitza": "landu", "sinonimoak": ["jaso", "zaindu", "laboratu"]},
  {"id": "3-125", "hitza": "lanpas", "sinonimoak": ["zerria"]},
  {"id": "3-126", "hitza": "latz", "sinonimoak": ["gogor", "bortitz", "zail"]},
  {"id": "3-127", "hitza": "laudorio", "sinonimoak": ["goraipamen", "gorespen", "handiespen"]},
  {"id": "3-128", "hitza": "lausengu", "sinonimoak": ["losintxa", "koipekeria", "balaku"]},
  {"id": "3-129", "hitza": "laztan", "sinonimoak": ["fereka", "txera"]},
  {"id": "3-130", "hitza": "legetxe", "sinonimoak": ["legez", "bezala", "adina"]},
  {"id": "3-131", "hitza": "lehenengo", "sinonimoak": ["lehenbiziko", "aurreneko", "estreinako"]},
  {"id": "3-132", "hitza": "lehengo", "sinonimoak": ["aurreko"]},
  {"id": "3-133", "hitza": "lehia", "sinonimoak": ["borroka", "norgehiagoka", "konkurrentzia"]},
  {"id": "3-134", "hitza": "leize", "sinonimoak": ["kobatzulo", "hatizulo"]},
  {"id": "3-135", "hitza": "lekukotu", "sinonimoak": ["bertakotu", "tokikotu", "sustraitu"]},
  {"id": "3-136", "hitza": "leporaino", "sinonimoak": ["goraino", "beterik", "gainezka"]},
  {"id": "3-137", "hitza": "lerde", "sinonimoak": ["adur"]},
  {"id": "3-138", "hitza": "lerdendu", "sinonimoak": ["liraindu", "zardaitu", "edertu"]},
  {"id": "3-139", "hitza": "leundu", "sinonimoak": ["bigundu", "baretu", "eztitu"]},
  {"id": "3-140", "hitza": "libro", "sinonimoak": ["aske", "libre", "nahierara"]},
  {"id": "3-141", "hitza": "ligain", "sinonimoak": ["gartxu", "jangartxu", "jangurarik gabe"]},
  {"id": "3-142", "hitza": "likits", "sinonimoak": ["zikin", "lizun", "lohi"]},
  {"id": "3-143", "hitza": "lili", "sinonimoak": ["lore"]},
  {"id": "3-144", "hitza": "liluragarri", "sinonimoak": ["xarmagarri", "zoragarri", "itsugarri"]},
  {"id": "3-145", "hitza": "lipar", "sinonimoak": ["une", "istant", "aldiune"]},
  {"id": "3-146", "hitza": "liskar", "sinonimoak": ["iskanbila", "haserre", "ika-mika"]},
  {"id": "3-147", "hitza": "lixiba", "sinonimoak": ["bokata", "gobada"]},
  {"id": "3-148", "hitza": "lodrot", "sinonimoak": ["lodi", "gizen", "potolo"]},
  {"id": "3-149", "hitza": "lokarri", "sinonimoak": ["axubeta", "estekailu"]},
  {"id": "3-150", "hitza": "loriagarri", "sinonimoak": ["zoragarri", "liluragarri", "txundigarri"]},
  {"id": "3-151", "hitza": "lorratz", "sinonimoak": ["aztarna", "oinatz", "herexe"]},
  {"id": "3-152", "hitza": "lumatu", "sinonimoak": ["bipildu", "ziplatu"]},
  {"id": "3-153", "hitza": "luzetsi", "sinonimoak": ["berantetsi", "kezkatu", "larritu"]},
  {"id": "3-154", "hitza": "magal", "sinonimoak": ["altzo", "galtzar", "kolko"]},
  {"id": "3-155", "hitza": "mahaikide", "sinonimoak": ["bazkaltiar", "bazkalkide", "jankide"]},
  {"id": "3-156", "hitza": "mainontzi", "sinonimoak": ["mainati", "negarti", "negarrontzi"]},
  {"id": "3-157", "hitza": "maisutasun", "sinonimoak": ["trebetasun", "abilezia", "maina"]},
  {"id": "3-158", "hitza": "maitagarri", "sinonimoak": ["zoragarri", "liluragarri", "xarmagarri"]},
  {"id": "3-159", "hitza": "maitale", "sinonimoak": ["amorante", "ohaide", "ohelagun"]},
  {"id": "3-160", "hitza": "maiztasun", "sinonimoak": ["sarritasun", "ohikotasun", "jarraitutasun"]},
  {"id": "3-161", "hitza": "maizter", "sinonimoak": ["errentari", "akuradun", "etxetiar"]},
  {"id": "3-162", "hitza": "makur", "sinonimoak": ["donge", "zital", "gaizto"]},
  {"id": "3-163", "hitza": "marmar", "sinonimoak": ["xuxurla", "murrmurio", "txutxu-mutxu"]},
  {"id": "3-164", "hitza": "maskal", "sinonimoak": ["makal", "ahul", "pattal"]},
  {"id": "3-165", "hitza": "mehar", "sinonimoak": ["estu", "hertsi", "itxi"]},
  {"id": "3-166", "hitza": "mehats", "sinonimoak": ["argal", "mehe", "makar"]},
  {"id": "3-167", "hitza": "mehatxu", "sinonimoak": ["zemai", "dixidu"]},
  {"id": "3-168", "hitza": "melatu", "sinonimoak": ["busti", "blaitu"]},
  {"id": "3-169", "hitza": "mendratu", "sinonimoak": ["gutxitu", "urritu", "eskastu"]},
  {"id": "3-170", "hitza": "mesedegarri", "sinonimoak": ["lagungarri", "onuragarri", "probetxugarri"]},
  {"id": "3-171", "hitza": "mihi", "sinonimoak": ["mingain"]},
  {"id": "3-172", "hitza": "mihise", "sinonimoak": ["izara", "maindire"]},
  {"id": "3-173", "hitza": "mikatz", "sinonimoak": ["mingots", "mingar", "karmin"]},
  {"id": "3-174", "hitza": "milika", "sinonimoak": ["mizkin", "milinga"]},
  {"id": "3-175", "hitza": "mintzagai", "sinonimoak": ["hizpide", "berbabide", "elepide"]},
  {"id": "3-176", "hitza": "mirabe", "sinonimoak": ["morroi", "otsein", "sehi"]},
  {"id": "3-177", "hitza": "mirail", "sinonimoak": ["ispilu"]},
  {"id": "3-178", "hitza": "moduzkotasun", "sinonimoak": ["apaintasun", "garbitasun", "txukuntasun"]},
  {"id": "3-179", "hitza": "moja", "sinonimoak": ["lekaime", "serora"]},
  {"id": "3-180", "hitza": "mokoka", "sinonimoak": ["errietan", "ika-mikan", "sesioan"]},
  {"id": "3-181", "hitza": "mokordo", "sinonimoak": ["lotsagabe", "petral", "ozar"]},
  {"id": "3-182", "hitza": "moldatu", "sinonimoak": ["konpondu"]},
  {"id": "3-183", "hitza": "mordotu", "sinonimoak": ["pilatu", "metatu", "bildu"]},
  {"id": "3-184", "hitza": "motroilo", "sinonimoak": ["potxolo", "pipor", "zaparrote"]},
  {"id": "3-185", "hitza": "mozkindu", "sinonimoak": ["sardakatu", "inausi", "kimatu"]},
  {"id": "3-186", "hitza": "mudakortasun", "sinonimoak": ["ezegonkortasun", "aldakortasun", "aldaberatasun"]},
  {"id": "3-187", "hitza": "mugarri", "sinonimoak": ["zedarri", "mugalde", "mutur"]},
  {"id": "3-188", "hitza": "mukizu", "sinonimoak": ["umemoko", "umegorri", "umekondo"]},
  {"id": "3-189", "hitza": "mukuru", "sinonimoak": ["beteta", "gainezka", "lepo"]},
  {"id": "3-190", "hitza": "murriztu", "sinonimoak": ["beheratu", "gutxitu"]},
  {"id": "3-191", "hitza": "musu-truk", "sinonimoak": ["doan", "debalde", "urririk"]},
  {"id": "3-192", "hitza": "mutildu", "sinonimoak": ["lumatu", "bipildu"]},
  {"id": "3-193", "hitza": "muturreko", "sinonimoak": ["ukabilko", "zartako", "ukabilkada"]},
  {"id": "3-194", "hitza": "ñabardura", "sinonimoak": ["xehetasun", "zehaztasun", "zehazkizun"]},
  {"id": "3-195", "hitza": "nabaritu", "sinonimoak": ["nabarmendu", "igarri", "antzeman"]},
  {"id": "3-196", "hitza": "nabarri", "sinonimoak": ["harrinabar"]},
  {"id": "3-197", "hitza": "nagikeria", "sinonimoak": ["alferkeria", "zabarkeria", "utzikeria"]},
  {"id": "3-198", "hitza": "nagusitu", "sinonimoak": ["gailendu", "garaitu", "nabarmendu"]},
  {"id": "3-199", "hitza": "nahasgarri", "sinonimoak": ["nahasi", "nahaspilatsu", "ilun"]},
  {"id": "3-200", "hitza": "nahikari", "sinonimoak": ["desira", "irrika", "lera"]}
];