import { WordData } from './types';

export const LEVEL_3_PART_1: WordData[] = [
  {"id": "3-1", "hitza": "inoiz", "sinonimoak": ["sekula", "egundo", "nehoiz"]},
  {"id": "3-2", "hitza": "inozokeria", "sinonimoak": ["lelokeria", "tentelkeria", "ergelkeria"]},
  {"id": "3-3", "hitza": "instituzio", "sinonimoak": ["erakunde"]},
  {"id": "3-4", "hitza": "intziri", "sinonimoak": ["aiene", "auhen", "erosta"]},
  {"id": "3-5", "hitza": "inurritu", "sinonimoak": ["lokartu", "sorgortu", "logaletu"]},
  {"id": "3-6", "hitza": "ipini", "sinonimoak": ["jarri", "paratu"]},
  {"id": "3-7", "hitza": "ipurdiko", "sinonimoak": ["ipurkada", "ipurdikada", "mokorkada"]},
  {"id": "3-8", "hitza": "ipurterre", "sinonimoak": ["erretxin", "kakapirri", "triperre"]},
  {"id": "3-9", "hitza": "irabazkin", "sinonimoak": ["mozkin", "etekin", "hobari"]},
  {"id": "3-10", "hitza": "iragaitza", "sinonimoak": ["bide", "iriste", "iragate"]},
  {"id": "3-11", "hitza": "iragarri", "sinonimoak": ["jakinarazi", "aditzera eman", "adierazi"]},
  {"id": "3-12", "hitza": "iraindu", "sinonimoak": ["laidotu", "laidoztatu", "laidetsi"]},
  {"id": "3-13", "hitza": "iraitz", "sinonimoak": ["bota", "egotzi", "bidali"]},
  {"id": "3-14", "hitza": "iratzarri", "sinonimoak": ["esnatu", "atzarrri", "ernatu"]},
  {"id": "3-15", "hitza": "iraungi", "sinonimoak": ["itzali", "amatatu", "hil"]},
  {"id": "3-16", "hitza": "iraunkor", "sinonimoak": ["etengabe", "jarraitu", "iragangaitz"]},
  {"id": "3-17", "hitza": "ireki", "sinonimoak": ["zabaldu"]},
  {"id": "3-18", "hitza": "irion", "sinonimoak": ["gastatu", "xahutu", "zarrasteldu"]},
  {"id": "3-19", "hitza": "irmotasun", "sinonimoak": ["sendotasun", "tinkotasun", "finkotasun"]},
  {"id": "3-20", "hitza": "irrigarri", "sinonimoak": ["barregarri", "lotsagarri"]},
  {"id": "3-21", "hitza": "isilean", "sinonimoak": ["ezkutuan", "sekretupean", "isilpean"]},
  {"id": "3-22", "hitza": "iskanbila", "sinonimoak": ["liskar", "kalapita", "zalaparta"]},
  {"id": "3-23", "hitza": "istinga", "sinonimoak": ["lupetza", "lokatza", "basatza"]},
  {"id": "3-24", "hitza": "istorio", "sinonimoak": ["pasadizo", "kontu"]},
  {"id": "3-25", "hitza": "itsu-itsuan", "sinonimoak": ["itsumustuka", "itsutuki", "itsuki"]},
  {"id": "3-26", "hitza": "itsukeria", "sinonimoak": ["setakeria", "egoskorkeria", "burugogorkeria"]},
  {"id": "3-27", "hitza": "itzalpe", "sinonimoak": ["gerizpe", "geriza", "itzal"]},
  {"id": "3-28", "hitza": "itzelezko", "sinonimoak": ["izugarrizko", "ikaragarrizko", "sekulako"]},
  {"id": "3-29", "hitza": "izenburu", "sinonimoak": ["idazpuru", "titulu", "goiburuko"]},
  {"id": "3-30", "hitza": "izenpetu", "sinonimoak": ["sinatu", "firmatu"]},
  {"id": "3-31", "hitza": "izotz", "sinonimoak": ["jela", "horma", "lei"]},
  {"id": "3-32", "hitza": "izuti", "sinonimoak": ["beldurti", "ikarati", "koldar"]},
  {"id": "3-33", "hitza": "jabaldu", "sinonimoak": ["lasaitu", "baretu", "trankildu"]},
  {"id": "3-34", "hitza": "jagon", "sinonimoak": ["zaindu", "artatu", "begiratu"]},
  {"id": "3-35", "hitza": "jai", "sinonimoak": ["festa", "besta"]},
  {"id": "3-36", "hitza": "jaiki", "sinonimoak": ["altxatu"]},
  {"id": "3-37", "hitza": "jaioterri", "sinonimoak": ["sorterri"]},
  {"id": "3-38", "hitza": "jaitsiera", "sinonimoak": ["beheratze", "beherakada", "jaiste"]},
  {"id": "3-39", "hitza": "jaki", "sinonimoak": ["elikagai", "janari", "jangai"]},
  {"id": "3-40", "hitza": "jakin", "sinonimoak": ["zehatz", "berezi", "konkretu"]},
  {"id": "3-41", "hitza": "jakin", "sinonimoak": ["ezagun", "ageriko", "nabari"]},
  {"id": "3-42", "hitza": "jakina", "sinonimoak": ["horixe", "noski", "hobe ez"]},
  {"id": "3-43", "hitza": "jakitate", "sinonimoak": ["jakituria", "jakinduria", "jakintasun"]},
  {"id": "3-44", "hitza": "jangale", "sinonimoak": ["jangura", "apetitu"]},
  {"id": "3-45", "hitza": "jantzi", "sinonimoak": ["ikasi", "jakitun", "jakintsu"]},
  {"id": "3-46", "hitza": "jantzitegi", "sinonimoak": ["arropategi", "aldagela"]},
  {"id": "3-47", "hitza": "jaurti", "sinonimoak": ["bota", "egotzi", "esan"]},
  {"id": "3-48", "hitza": "jausi", "sinonimoak": ["erori"]},
  {"id": "3-49", "hitza": "jelatu", "sinonimoak": ["izoztu", "hormatu", "leitu"]},
  {"id": "3-50", "hitza": "jeloskeria", "sinonimoak": ["bekaizkeria", "inbidia", "ondamu"]},
  {"id": "3-51", "hitza": "jendetasun", "sinonimoak": ["gizalege", "adeitasun", "gizabide"]},
  {"id": "3-52", "hitza": "jendetza", "sinonimoak": ["jendeketa", "jendealdia", "jende-pila"]},
  {"id": "3-53", "hitza": "jesan", "sinonimoak": ["usteko eskatu"]},
  {"id": "3-54", "hitza": "jesarri", "sinonimoak": ["eseri", "jarri", "kokatu"]},
  {"id": "3-55", "hitza": "jetzi", "sinonimoak": ["bildu"]},
  {"id": "3-56", "hitza": "jeurt egin", "sinonimoak": ["atzera egin"]},
  {"id": "3-57", "hitza": "jin", "sinonimoak": ["etorri"]},
  {"id": "3-58", "hitza": "jipoi", "sinonimoak": ["astindu", "astinaldi", "astinketa"]},
  {"id": "3-59", "hitza": "jirabira", "sinonimoak": ["itzulinguru", "ingurumari"]},
  {"id": "3-60", "hitza": "jiratu", "sinonimoak": ["biratu", "bihurtu", "itzuli"]},
  {"id": "3-61", "hitza": "jitoan", "sinonimoak": ["noraezean"]},
  {"id": "3-62", "hitza": "joaldi", "sinonimoak": ["kontzertu", "emanaldi", "saio"]},
  {"id": "3-63", "hitza": "joera", "sinonimoak": ["jaugin", "grina", "ganu"]},
  {"id": "3-64", "hitza": "jokabide", "sinonimoak": ["jokaera", "jokamolde", "portaera"]},
  {"id": "3-65", "hitza": "jomuga", "sinonimoak": ["helburu", "xede"]},
  {"id": "3-66", "hitza": "jorratu", "sinonimoak": ["landu", "aztertu", "ikusi"]},
  {"id": "3-67", "hitza": "josi", "sinonimoak": ["bete", "gainezka", "mukuru"]},
  {"id": "3-68", "hitza": "josteta", "sinonimoak": ["olgeta", "jolas", "jostaketa"]},
  {"id": "3-69", "hitza": "juje", "sinonimoak": ["epaile", "jujari"]},
  {"id": "3-70", "hitza": "jukutria", "sinonimoak": ["txandrio", "azpijoko", "azpikeria"]},
  {"id": "3-71", "hitza": "junpatu", "sinonimoak": ["kulunkatu", "zabunkatu", "zarabandatu"]},
  {"id": "3-72", "hitza": "juzgu", "sinonimoak": ["iritzi", "uste", "aburu"]},
  {"id": "3-73", "hitza": "kabartu", "sinonimoak": ["lehortu", "idortu", "sikatu"]},
  {"id": "3-74", "hitza": "kabugabe", "sinonimoak": ["amaigabe", "azkengabe", "mugagabe"]},
  {"id": "3-75", "hitza": "kadira", "sinonimoak": ["jarleku", "aulki", "jesarleku"]},
  {"id": "3-76", "hitza": "kaialde", "sinonimoak": ["portualde"]},
  {"id": "3-77", "hitza": "kailutsu", "sinonimoak": ["mehar", "mehe", "argal"]},
  {"id": "3-78", "hitza": "kaio", "sinonimoak": ["antxeta", "kalatxori"]},
  {"id": "3-79", "hitza": "kakazkeria", "sinonimoak": ["doilorkeria", "zitalkeria", "gizatzarkeria"]},
  {"id": "3-80", "hitza": "kakaztu", "sinonimoak": ["zapuztu", "hondatu", "alferrik galdu"]},
  {"id": "3-81", "hitza": "kalte", "sinonimoak": ["gaitz", "min"]},
  {"id": "3-82", "hitza": "kamuts", "sinonimoak": ["makets", "lanputs"]},
  {"id": "3-83", "hitza": "kaskutsik", "sinonimoak": ["buru hutsik"]},
  {"id": "3-84", "hitza": "katanarru", "sinonimoak": ["diru-zorroa"]},
  {"id": "3-85", "hitza": "kebide", "sinonimoak": ["kezulo", "tximinia"]},
  {"id": "3-86", "hitza": "keinatu", "sinonimoak": ["mehatxatu", "zemaitu", "larderiatu"]},
  {"id": "3-87", "hitza": "keko-meko", "sinonimoak": ["zalantzati", "dudatsu", "ezbaiti"]},
  {"id": "3-88", "hitza": "kemen", "sinonimoak": ["gogo", "adore", "kalipu"]},
  {"id": "3-89", "hitza": "kerratu", "sinonimoak": ["galdu", "mindu", "garraztu"]},
  {"id": "3-90", "hitza": "keru", "sinonimoak": ["kirats", "sunda", "hats"]},
  {"id": "3-91", "hitza": "kexa", "sinonimoak": ["kexu", "arrangura", "auhen"]},
  {"id": "3-92", "hitza": "kezkatu", "sinonimoak": ["arduratu", "larritu", "urduritu"]},
  {"id": "3-93", "hitza": "kideko", "sinonimoak": ["antzeko", "berdintsu", "pareko"]},
  {"id": "3-94", "hitza": "kikirrio", "sinonimoak": ["zakil", "buztan", "armagi"]},
  {"id": "3-95", "hitza": "kilimon", "sinonimoak": ["porrot", "molokot", "kiebra"]},
  {"id": "3-96", "hitza": "kimatu", "sinonimoak": ["inausi", "adaondu", "moztu"]},
  {"id": "3-97", "hitza": "kimu", "sinonimoak": ["puja", "aldaxka", "muskil"]},
  {"id": "3-98", "hitza": "kirian", "sinonimoak": ["segidan", "ordenan", "hurrenkeran"]},
  {"id": "3-99", "hitza": "kirten", "sinonimoak": ["gider", "helduleku", "eskuleku"]},
  {"id": "3-100", "hitza": "kiskilkeria", "sinonimoak": ["bilaukeria", "zitalkeria", "dongekeria"]}
];