import { WordData } from './types';

export const LEVEL_4_PART_2: WordData[] = [
 {"id": "4-101", "hitza": "taka-taka", "sinonimoak": ["tipi-tapa", "pitinka-pitinka", "gutxika-gutxika"]},
  {"id": "4-102", "hitza": "talapastatu", "sinonimoak": ["nahasi", "nahastatu", "irauli"]},
  {"id": "4-103", "hitza": "taldekatu", "sinonimoak": ["multzokatu", "elkartu", "batu"]},
  {"id": "4-104", "hitza": "talka", "sinonimoak": ["kolpe", "danbateko", "kroska"]},
  {"id": "4-105", "hitza": "tamainan", "sinonimoak": ["primeran", "ederto", "bikain"]},
  {"id": "4-106", "hitza": "tamalgarri", "sinonimoak": ["penagarri", "deitoragarri", "damugarri"]},
  {"id": "4-107", "hitza": "tanatu", "sinonimoak": ["Ilea jausi", "Ilea erori", "Ilea galdu"]},
  {"id": "4-108", "hitza": "tankera", "sinonimoak": ["itxura", "eite", "irudi"]},
  {"id": "4-109", "hitza": "tapaki", "sinonimoak": ["burusi", "manta"]},
  {"id": "4-110", "hitza": "tarrapatan", "sinonimoak": ["arrapaladan", "zistuan", "itsumustuan"]},
  {"id": "4-111", "hitza": "taxu", "sinonimoak": ["maina", "trebezia", "arte"]},
  {"id": "4-112", "hitza": "taxutu", "sinonimoak": ["prestatu", "antolatu", "eratu"]},
  {"id": "4-113", "hitza": "teiu", "sinonimoak": ["lizun", "likits", "lohi"]},
  {"id": "4-114", "hitza": "teku", "sinonimoak": ["kirats", "keru", "sunda"]},
  {"id": "4-115", "hitza": "tenperaturan", "sinonimoak": ["hozbero"]},
  {"id": "4-116", "hitza": "tentagarri", "sinonimoak": ["erakargarri", "zirikagarri", "desiragarri"]},
  {"id": "4-117", "hitza": "tenteldu", "sinonimoak": ["txepeldu", "tontotu", "ergeldu"]},
  {"id": "4-118", "hitza": "tentetu", "sinonimoak": ["zutitu", "zutundu"]},
  {"id": "4-119", "hitza": "tentu", "sinonimoak": ["sen", "zentzu"]},
  {"id": "4-120", "hitza": "terrenta", "sinonimoak": ["ohikeria", "errutina", "ohitura"]},
  {"id": "4-121", "hitza": "testigu", "sinonimoak": ["lekuko"]},
  {"id": "4-122", "hitza": "testuinguru", "sinonimoak": ["ingurubar", "ingurune", "egoera"]},
  {"id": "4-123", "hitza": "tetele-metele", "sinonimoak": ["tontoki", "axolagabeki", "funsgabeki"]},
  {"id": "4-124", "hitza": "tinko", "sinonimoak": ["sendo", "irmo", "finko"]},
  {"id": "4-125", "hitza": "tirabira", "sinonimoak": ["liskar", "eztabaida", "kalapita"]},
  {"id": "4-126", "hitza": "tiragale", "sinonimoak": ["nagi", "sagai"]},
  {"id": "4-127", "hitza": "tirriagarri", "sinonimoak": ["desiragarri", "tentagarri", "erakargarri"]},
  {"id": "4-128", "hitza": "tirtirin", "sinonimoak": ["poxpolin", "pertxenta", "mari-apain"]},
  {"id": "4-129", "hitza": "toildu", "sinonimoak": ["nagitu", "alfertu", "zabartu"]},
  {"id": "4-130", "hitza": "tokolo", "sinonimoak": ["potolo", "lodikote", "papalote"]},
  {"id": "4-131", "hitza": "tontor", "sinonimoak": ["gailur", "erpin", "gain"]},
  {"id": "4-132", "hitza": "tortilla", "sinonimoak": ["arrautzopil"]},
  {"id": "4-133", "hitza": "traba", "sinonimoak": ["oztopo", "enbarazu", "eragozpen"]},
  {"id": "4-134", "hitza": "trankildu", "sinonimoak": ["naretu", "lasaitu", "ibitu"]},
  {"id": "4-135", "hitza": "tranpati", "sinonimoak": ["iruzurti", "amarrutsu", "azpijale"]},
  {"id": "4-136", "hitza": "trapadu", "sinonimoak": ["mozkote", "potolo", "zaparrote"]},
  {"id": "4-137", "hitza": "tratu", "sinonimoak": ["harreman", "tratabide", "erlazio"]},
  {"id": "4-138", "hitza": "trebatu", "sinonimoak": ["gaitu", "hornitu", "ikasi"]},
  {"id": "4-139", "hitza": "trenkatu", "sinonimoak": ["moztu", "eragotzi", "oztopatu"]},
  {"id": "4-140", "hitza": "trimindu", "sinonimoak": ["txikitu", "suntsitu", "birrindu"]},
  {"id": "4-141", "hitza": "triskilatu", "sinonimoak": ["suntsitu", "txikitu", "birrindu"]},
  {"id": "4-142", "hitza": "tronpatu", "sinonimoak": ["erratu", "okertu", "nahastu"]},
  {"id": "4-143", "hitza": "trufa", "sinonimoak": ["iseka", "burla", "txantxa"]},
  {"id": "4-144", "hitza": "trukatu", "sinonimoak": ["eman", "egin", "aldatu"]},
  {"id": "4-145", "hitza": "trumil", "sinonimoak": ["tropel", "saldo", "samalda"]},
  {"id": "4-146", "hitza": "tunka", "sinonimoak": ["umore", "aldarte", "gogo"]},
  {"id": "4-147", "hitza": "txainku", "sinonimoak": ["herren", "maingu", "trankin"]},
  {"id": "4-148", "hitza": "txaldantu", "sinonimoak": ["txepeldu", "ergeldu", "lelotu"]},
  {"id": "4-149", "hitza": "txalogarri", "sinonimoak": ["laudagarri", "goresgarri", "goragarri"]},
  {"id": "4-150", "hitza": "txanbil", "sinonimoak": ["pegar", "suil", "txantxil"]},
  {"id": "4-151", "hitza": "txarkeria", "sinonimoak": ["gaiztakeria", "bihurrikeria", "deabrukeria"]},
  {"id": "4-152", "hitza": "txarretsi", "sinonimoak": ["gaitzetsi", "ezetsi", "hastandu"]},
  {"id": "4-153", "hitza": "txatxu", "sinonimoak": ["txotxolo", "txepel", "ganorabako"]},
  {"id": "4-154", "hitza": "txepeldu", "sinonimoak": ["kikildu", "beldurtu", "koldartu"]},
  {"id": "4-155", "hitza": "txerrikeria", "sinonimoak": ["zikinkeria", "lohi", "zabor"]},
  {"id": "4-156", "hitza": "txertatu", "sinonimoak": ["eman", "tartekatu", "egokitu"]},
  {"id": "4-157", "hitza": "txikertu", "sinonimoak": ["txiki(ago)tu", "murriztu", "gutxitu"]},
  {"id": "4-158", "hitza": "txikietsi", "sinonimoak": ["mespretxatu", "erdeinatu", "gutxietsi"]},
  {"id": "4-159", "hitza": "tximarro", "sinonimoak": ["txima", "zarpa", "ilaje"]},
  {"id": "4-160", "hitza": "tximista", "sinonimoak": ["oinaztura", "oinaztarri", "oinazkar"]},
  {"id": "4-161", "hitza": "txintxo", "sinonimoak": ["formal", "on", "zentzuzko"]},
  {"id": "4-162", "hitza": "txiripa", "sinonimoak": ["zorte", "zori", "asturu"]},
  {"id": "4-163", "hitza": "txiro", "sinonimoak": ["pobre", "behartsu", "lander"]},
  {"id": "4-164", "hitza": "txirriporro", "sinonimoak": ["zalaparta", "harrabots", "zarata"]},
  {"id": "4-165", "hitza": "txirrist", "sinonimoak": ["laprast", "labain", "irrist"]},
  {"id": "4-166", "hitza": "txit", "sinonimoak": ["guztiz", "zeharo", "biziki"]},
  {"id": "4-167", "hitza": "txitean-pitean", "sinonimoak": ["maiz", "sarri", "usu"]},
  {"id": "4-168", "hitza": "txo", "sinonimoak": ["to", "txotxo", "motel"]},
  {"id": "4-169", "hitza": "txoil", "sinonimoak": ["guztiz", "erabat", "arras"]},
  {"id": "4-170", "hitza": "txoratu", "sinonimoak": ["txora-txora egin", "liluratu", "xarmatu"]},
  {"id": "4-171", "hitza": "txorrotxio", "sinonimoak": ["txio", "txinta", "txiruliru"]},
  {"id": "4-172", "hitza": "txortan", "sinonimoak": ["larrutan", "ñaka", "txikili-txakala"]},
  {"id": "4-173", "hitza": "txotxin", "sinonimoak": ["kaskarin", "txolin", "txoriburu"]},
  {"id": "4-174", "hitza": "txukundu", "sinonimoak": ["egokitu", "prestatu", "atondu"]},
  {"id": "4-175", "hitza": "txundigarri", "sinonimoak": ["harrigarri", "espantagarri", "bitxi"]},
  {"id": "4-176", "hitza": "txuntxur", "sinonimoak": ["tontor", "gailur", "gain"]},
  {"id": "4-177", "hitza": "ubeldu", "sinonimoak": ["ilundu", "belztu", "goibeldu"]},
  {"id": "4-178", "hitza": "ubide", "sinonimoak": ["ibilgu", "ibilbide", "erreten"]},
  {"id": "4-179", "hitza": "udagoien", "sinonimoak": ["udazken"]},
  {"id": "4-180", "hitza": "udaletxe", "sinonimoak": ["herriko etxe", "herri-etxe"]},
  {"id": "4-181", "hitza": "udare", "sinonimoak": ["madari"]},
  {"id": "4-182", "hitza": "ugaldu", "sinonimoak": ["ugaritu", "gehiagotu", "areagotu"]},
  {"id": "4-183", "hitza": "ugazaba", "sinonimoak": ["nagusi"]},
  {"id": "4-184", "hitza": "uger", "sinonimoak": ["herdoil", "oxido"]},
  {"id": "4-185", "hitza": "uhanditu", "sinonimoak": ["harropuztu", "hanpatu", "harrotu"]},
  {"id": "4-186", "hitza": "uhara", "sinonimoak": ["ubera", "lorratz", "arrasto"]},
  {"id": "4-187", "hitza": "ukazio", "sinonimoak": ["ukapen", "ezezko", "ukamen"]},
  {"id": "4-188", "hitza": "ukuilu", "sinonimoak": ["korta", "abeltegi"]},
  {"id": "4-189", "hitza": "ulerkor", "sinonimoak": ["adikor", "adeitsu", "harkor"]},
  {"id": "4-190", "hitza": "ulituko", "sinonimoak": ["koldartuko", "kikilduko", "uzkurtuko"]},
  {"id": "4-191", "hitza": "ulu", "sinonimoak": ["uhuri", "ainuri"]},
  {"id": "4-192", "hitza": "umeldu", "sinonimoak": ["hezetu", "ezkotu", "busti"]},
  {"id": "4-193", "hitza": "umeteria", "sinonimoak": ["haurreria", "haur-talde", "haur-jende"]},
  {"id": "4-194", "hitza": "umil", "sinonimoak": ["apal", "xume", "xehe"]},
  {"id": "4-195", "hitza": "umoretsu", "sinonimoak": ["pozik", "alai", "alegera"]},
  {"id": "4-196", "hitza": "umotu", "sinonimoak": ["heldu", "ondu", "zoritu"]},
  {"id": "4-197", "hitza": "unagarri", "sinonimoak": ["nekagarri", "aspergarri", "gogaikarri"]},
  {"id": "4-198", "hitza": "upategi", "sinonimoak": ["arandegi", "ardangela", "upeletegi"]},
  {"id": "4-199", "hitza": "uraldi", "sinonimoak": ["uholde", "urpetze"]},
  {"id": "4-200", "hitza": "urardotu", "sinonimoak": ["hutsaldu", "desitxuratu", "desnaturalizatu"]}
];