import { WordData } from './types';

export const LEVEL_2_PART_1: WordData[] = [
  {"id": "2-1", "hitza": "abaraska", "sinonimoak": ["orraze", "abao", "ezti-orraze"]},
  {"id": "2-2", "hitza": "abiapuntu", "sinonimoak": ["abiaburu", "hastapen", "hasiera"]},
  {"id": "2-3", "hitza": "abizen", "sinonimoak": ["deitura"]},
  {"id": "2-4", "hitza": "aburuz", "sinonimoak": ["ustez", "iritziz", "irudiko(z)"]},
  {"id": "2-5", "hitza": "adabaki", "sinonimoak": ["txaplata", "txatal", "petatxu"]},
  {"id": "2-6", "hitza": "adats", "sinonimoak": ["ilaje", "menats", "motots"]},
  {"id": "2-7", "hitza": "adeitsu", "sinonimoak": ["gizabidetsu", "xalo", "atsegin"]},
  {"id": "2-8", "hitza": "adimen", "sinonimoak": ["ulermen", "adimendu", "endelgu"]},
  {"id": "2-9", "hitza": "adindu", "sinonimoak": ["zahartu"]},
  {"id": "2-10", "hitza": "adoretsu", "sinonimoak": ["gartsu", "kementsu", "bipil"]},
  {"id": "2-11", "hitza": "afaloste", "sinonimoak": ["afalondo"]},
  {"id": "2-12", "hitza": "afan", "sinonimoak": ["joran", "lehia", "gogo"]},
  {"id": "2-13", "hitza": "aforo", "sinonimoak": ["edukiera", "leku", "toki"]},
  {"id": "2-14", "hitza": "agergarri", "sinonimoak": ["froga", "erakusgarri", "adierazgarri"]},
  {"id": "2-15", "hitza": "agerkari", "sinonimoak": ["argitalpen"]},
  {"id": "2-16", "hitza": "agerkunde", "sinonimoak": ["agerpen", "agerraldi", "agertze"]},
  {"id": "2-17", "hitza": "agian", "sinonimoak": ["apika", "beharbada", "akaso", "menturaz", "ausaz"]},
  {"id": "2-18", "hitza": "agindu", "sinonimoak": ["prometatu", "hitzeman", "promes egin"]},
  {"id": "2-19", "hitza": "agintari", "sinonimoak": ["buruzagi", "buru", "nagusi"]},
  {"id": "2-20", "hitza": "agiraka", "sinonimoak": ["errieta", "haserre", "ahakar"]},
  {"id": "2-21", "hitza": "agiri", "sinonimoak": ["idazki", "dokumentu"]},
  {"id": "2-22", "hitza": "agitu", "sinonimoak": ["gertatu", "jazo"]},
  {"id": "2-23", "hitza": "agorril", "sinonimoak": ["abuztu", "dagonil"]},
  {"id": "2-24", "hitza": "agorte", "sinonimoak": ["lehorte", "sikate", "agorraldi"]},
  {"id": "2-25", "hitza": "aguazil", "sinonimoak": ["txinel", "udaltzain"]},
  {"id": "2-26", "hitza": "agudo", "sinonimoak": ["laster", "azkar", "fite", "bizkor"]},
  {"id": "2-27", "hitza": "agur", "sinonimoak": ["diosal", "adio"]},
  {"id": "2-28", "hitza": "agure", "sinonimoak": ["gizonezko zahar", "gizonezko adintsu", "aitona"]},
  {"id": "2-29", "hitza": "ahaide", "sinonimoak": ["senitarteko", "familiako"]},
  {"id": "2-30", "hitza": "ahaire", "sinonimoak": ["doinu", "melodia"]},
  {"id": "2-31", "hitza": "ahal den lasterren", "sinonimoak": ["lehenbailehen", "albait arinen", "ahalik eta azkarren"]},
  {"id": "2-32", "hitza": "badaezpadako", "sinonimoak": ["zalantzazko", "duda-mudako", "ezbaiko"]},
  {"id": "2-33", "hitza": "baga", "sinonimoak": ["uhin", "olatu"]},
  {"id": "2-34", "hitza": "bailara", "sinonimoak": ["haran", "ibar", "sakan"]},
  {"id": "2-35", "hitza": "baina", "sinonimoak": ["ordea", "hala ere", "alabaina"]},
  {"id": "2-36", "hitza": "bakan", "sinonimoak": ["banaka", "urri", "eskas"]},
  {"id": "2-37", "hitza": "baldarkeria", "sinonimoak": ["dorpekeria", "trakeskeria"]},
  {"id": "2-38", "hitza": "baztertu", "sinonimoak": ["zokoratu", "alboratu", "bazterreratu"]},
  {"id": "2-39", "hitza": "begiluze", "sinonimoak": ["kuxkuxero", "nontzeberri", "ikusmiratzaile"]},
  {"id": "2-40", "hitza": "begirale", "sinonimoak": ["jagole", "zaintzaile", "artatzaile"]},
  {"id": "2-41", "hitza": "begiramen", "sinonimoak": ["begirune", "errespetu"]},
  {"id": "2-42", "hitza": "belaunaldi", "sinonimoak": ["gizaldi"]},
  {"id": "2-43", "hitza": "beltzune", "sinonimoak": ["ubeldura", "ubelune", "belztasun"]},
  {"id": "2-44", "hitza": "beratu", "sinonimoak": ["bigundu", "leundu", "guritu"]},
  {"id": "2-45", "hitza": "bertute", "sinonimoak": ["dohain"]},
  {"id": "2-46", "hitza": "betebehar", "sinonimoak": ["zeregin", "eginkizun", "eginbehar"]},
  {"id": "2-47", "hitza": "beteta", "sinonimoak": ["lepo", "gainezka", "mukuru"]},
  {"id": "2-48", "hitza": "betilun", "sinonimoak": ["triste", "goibel", "hits"]},
  {"id": "2-49", "hitza": "bezatu", "sinonimoak": ["ohitu", "etxekotu", "otzandu", "mantsotu"]},
  {"id": "2-50", "hitza": "bider", "sinonimoak": ["aldiz"]},
  {"id": "2-51", "hitza": "bidezidor", "sinonimoak": ["bidexka", "xendra", "basabide"]},
  {"id": "2-52", "hitza": "bigun", "sinonimoak": ["leun", "guri", "samur"]},
  {"id": "2-53", "hitza": "bilakaera", "sinonimoak": ["eboluzio", "garapen", "eraldaketa"]},
  {"id": "2-54", "hitza": "biluzi", "sinonimoak": ["biluzgorri", "larrugorri"]},
  {"id": "2-55", "hitza": "bitxilore", "sinonimoak": ["txibirita"]},
  {"id": "2-56", "hitza": "bizibide", "sinonimoak": ["ogibide", "lanbide", "ofizio"]},
  {"id": "2-57", "hitza": "biziki", "sinonimoak": ["arras", "oso", "biziro"]},
  {"id": "2-58", "hitza": "blai-blai", "sinonimoak": ["mela-mela", "busti-busti", "zopatuta"]},
  {"id": "2-59", "hitza": "bokarta", "sinonimoak": ["antxoa"]},
  {"id": "2-60", "hitza": "borda", "sinonimoak": ["etxola", "txabola"]},
  {"id": "2-61", "hitza": "bordion", "sinonimoak": ["urdanga", "puta", "emagaldu", "maritzar", "julis"]},
  {"id": "2-62", "hitza": "borondate", "sinonimoak": ["gogo", "nahi", "desira"]},
  {"id": "2-63", "hitza": "borragoma", "sinonimoak": ["ezabagoma", "goma"]},
  {"id": "2-64", "hitza": "bortizkeria", "sinonimoak": ["indarkeria", "gogorkeria", "bortxakeria"]},
  {"id": "2-65", "hitza": "bozkario", "sinonimoak": ["poz", "alegrantzia", "poztasun"]},
  {"id": "2-66", "hitza": "bultzatzaile", "sinonimoak": ["sustatzaile", "eragile"]},
  {"id": "2-67", "hitza": "burugabe", "sinonimoak": ["txoro", "burtzoro", "zentzugabe"]},
  {"id": "2-68", "hitza": "burugogor", "sinonimoak": ["setatsu", "egoskor", "temati", "burugogor"]},
  {"id": "2-69", "hitza": "burutazio", "sinonimoak": ["ideia", "pentsamendu", "gomuta", "burutaldi", "burutapen"]},
  {"id": "2-70", "hitza": "burutu", "sinonimoak": ["gauzatu", "obratu", "mamitu"]},
  {"id": "2-71", "hitza": "buruz buruko", "sinonimoak": ["eskuz eskuko", "banakako", "bakarkako"]},
  {"id": "2-72", "hitza": "buztan", "sinonimoak": ["isats"]},
  {"id": "2-73", "hitza": "dailu", "sinonimoak": ["sega", "kodaina"]},
  {"id": "2-74", "hitza": "danbada", "sinonimoak": ["danbateko", "burrunba", "harrabots"]},
  {"id": "2-75", "hitza": "datu", "sinonimoak": ["argibide", "zehaztapen", "azalpen"]},
  {"id": "2-76", "hitza": "deblauki", "sinonimoak": ["bat-batean", "kolpetik", "supituki"]},
  {"id": "2-77", "hitza": "defendaezin", "sinonimoak": ["eutsiezin", "sostengaezin"]},
  {"id": "2-78", "hitza": "deiadar", "sinonimoak": ["oihu", "aldarri", "garrasi"]},
  {"id": "2-79", "hitza": "deitoragarri", "sinonimoak": ["negargarri", "tamalgarri", "penagarri"]},
  {"id": "2-80", "hitza": "deklarazio", "sinonimoak": ["adierazpen", "jakinarazpen", "azalpen"]},
  {"id": "2-81", "hitza": "dema", "sinonimoak": ["apustu", "postura"]},
  {"id": "2-82", "hitza": "dena dela", "sinonimoak": ["nolanahi ere", "edonola ere", "dena den"]},
  {"id": "2-83", "hitza": "denda", "sinonimoak": ["saltoki", "salgune", "saltegi"]},
  {"id": "2-84", "hitza": "deportatu", "sinonimoak": ["erbesteratu", "arroztu", "atzerriratu"]},
  {"id": "2-85", "hitza": "derrigorrezko", "sinonimoak": ["ezinbesteko", "nahitaezko", "halabeharrezko"]},
  {"id": "2-86", "hitza": "desberdindu", "sinonimoak": ["bereizi", "ezberdindu"]},
  {"id": "2-87", "hitza": "desenkusa", "sinonimoak": ["aitzakia", "estakuru"]},
  {"id": "2-88", "hitza": "desira", "sinonimoak": ["nahi", "gogo", "gurari"]},
  {"id": "2-89", "hitza": "deslai", "sinonimoak": ["egiteke", "solte"]},
  {"id": "2-90", "hitza": "destino", "sinonimoak": ["patu", "halabehar", "zori"]},
  {"id": "2-91", "hitza": "deus", "sinonimoak": ["ezer(txo)", "tutik", "fitsik"]},
  {"id": "2-92", "hitza": "dezente", "sinonimoak": ["nahiko", "aski", "askotxo"]},
  {"id": "2-93", "hitza": "dibortziatu", "sinonimoak": ["bereizi", "banandu", "bizi-alargundu"]},
  {"id": "2-94", "hitza": "dieta", "sinonimoak": ["jan-neurri", "jan-lege"]},
  {"id": "2-95", "hitza": "diferentzia", "sinonimoak": ["alde", "ezberdintasun", "desberdintasun"]},
  {"id": "2-96", "hitza": "dirukoi", "sinonimoak": ["diruzale", "zeken", "zikoitz"]},
  {"id": "2-97", "hitza": "dirutu", "sinonimoak": ["aberastu", "dirutza egin"]},
  {"id": "2-98", "hitza": "diruzalekeria", "sinonimoak": ["zekenkeria", "zikoizkeria"]},
  {"id": "2-99", "hitza": "distantzia", "sinonimoak": ["tarte", "bitarte"]},
  {"id": "2-100", "hitza": "dohakabeki", "sinonimoak": ["zoritxarrez", "tamalez", "maluruski", "ondikoz", "damurik"]}
];