import { WordData } from './types';

export const LEVEL_2_PART_3: WordData[] = [
  {"id": "2-201", "hitza": "gaitz", "sinonimoak": ["zail", "nekez"]},
  {"id": "2-202", "hitza": "gaixo", "sinonimoak": ["eri"]},
  {"id": "2-203", "hitza": "gaiztotu", "sinonimoak": ["zoldu", "zornatu", "gaizkoatu"]},
  {"id": "2-204", "hitza": "galbide", "sinonimoak": ["hondamendi", "hondamen", "galmen"]},
  {"id": "2-205", "hitza": "galdara", "sinonimoak": ["pertz", "eltze", "maskelu"]},
  {"id": "2-206", "hitza": "galdu", "sinonimoak": ["hondatu", "mindu", "alferrik galdu"]},
  {"id": "2-207", "hitza": "gale", "sinonimoak": ["desira", "nahi", "gogo"]},
  {"id": "2-208", "hitza": "galgatu", "sinonimoak": ["balaztatu", "geldiarazi", "gelditu"]},
  {"id": "2-209", "hitza": "gaurko", "sinonimoak": ["oraingo", "egungo", "gaur egungo"]},
  {"id": "2-210", "hitza": "gazi-geza", "sinonimoak": ["gazi-gozo"]},
  {"id": "2-211", "hitza": "gaztigu", "sinonimoak": ["abisu", "mezu", "jakinarazpen"]},
  {"id": "2-212", "hitza": "gela", "sinonimoak": ["areto", "sala"]},
  {"id": "2-213", "hitza": "geldiro", "sinonimoak": ["astiro", "poliki", "emeki"]},
  {"id": "2-214", "hitza": "gertaera", "sinonimoak": ["jazoera", "gertakari"]},
  {"id": "2-215", "hitza": "gibelalde", "sinonimoak": ["atzealde"]},
  {"id": "2-216", "hitza": "gisako", "sinonimoak": ["moduko", "antzeko", "pareko"]},
  {"id": "2-217", "hitza": "gizen", "sinonimoak": ["lodi", "potolo", "obeso"]},
  {"id": "2-218", "hitza": "gogoangarri", "sinonimoak": ["oroigarri", "gomutagarri", "gogoragarri"]},
  {"id": "2-219", "hitza": "gogoeta", "sinonimoak": ["hausnarketa", "pentsaketa", "azterketa"]},
  {"id": "2-220", "hitza": "gogoko", "sinonimoak": ["gustuko", "atsegin", "laket"]},
  {"id": "2-221", "hitza": "goibel", "sinonimoak": ["betilun", "triste", "hits"]},
  {"id": "2-222", "hitza": "goititu", "sinonimoak": ["altxatu", "jaso", "goratu"]},
  {"id": "2-223", "hitza": "gorabehera", "sinonimoak": ["aje", "gaitz", "min"]},
  {"id": "2-224", "hitza": "gorazarre", "sinonimoak": ["omenaldi"]},
  {"id": "2-225", "hitza": "gorputz", "sinonimoak": ["soin"]},
  {"id": "2-226", "hitza": "gorroto", "sinonimoak": ["herra", "higuin", "hegigo"]},
  {"id": "2-227", "hitza": "gotzain", "sinonimoak": ["apezpiku"]},
  {"id": "2-228", "hitza": "greba", "sinonimoak": ["lanuzte", "huelga"]},
  {"id": "2-229", "hitza": "gurdi", "sinonimoak": ["orga", "karro"]},
  {"id": "2-230", "hitza": "guritu", "sinonimoak": ["beratu", "bigundu", "samurtu"]},
  {"id": "2-231", "hitza": "gutizia", "sinonimoak": ["apeta", "gurari", "nahiera"]},
  {"id": "2-232", "hitza": "gutxi", "sinonimoak": ["eskas", "urri", "txiki"]},
  {"id": "2-233", "hitza": "haatik", "sinonimoak": ["hala ere", "alabaina", "alta"]},
  {"id": "2-234", "hitza": "hagin", "sinonimoak": ["hortz", "hortz-hagin", "hortzeria"]},
  {"id": "2-235", "hitza": "haitzulo", "sinonimoak": ["kobazulo", "leize", "harpe"]},
  {"id": "2-236", "hitza": "haizatu", "sinonimoak": ["aireztatu", "egurastu", "airatu"]},
  {"id": "2-237", "hitza": "hamarkada", "sinonimoak": ["hamarraldi", "hamarte"]},
  {"id": "2-238", "hitza": "hanpatu", "sinonimoak": ["puztu", "handitu", "hantu"]},
  {"id": "2-239", "hitza": "hantuste", "sinonimoak": ["harrokeria", "handikeria", "burgoikeria"]},
  {"id": "2-240", "hitza": "haran", "sinonimoak": ["bailara", "ibar", "sakan"]},
  {"id": "2-241", "hitza": "harraska", "sinonimoak": ["sukaltarri", "txurrutarri", "dala"]},
  {"id": "2-242", "hitza": "hautetsi", "sinonimoak": ["aukeratu", "hautatu", "izendatu"]},
  {"id": "2-243", "hitza": "heldu", "sinonimoak": ["umotu", "ondu", "zoritu"]},
  {"id": "2-244", "hitza": "herbal", "sinonimoak": ["ahul", "makal", "indarge"]},
  {"id": "2-245", "hitza": "herren", "sinonimoak": ["maingu", "trankin", "hanka-motz"]},
  {"id": "2-246", "hitza": "herrenbel", "sinonimoak": ["akastun", "narriodun"]},
  {"id": "2-247", "hitza": "hertsi", "sinonimoak": ["itxi", "estu", "mehar"]},
  {"id": "2-248", "hitza": "heze", "sinonimoak": ["umel", "ezko", "busti"]},
  {"id": "2-249", "hitza": "higitu", "sinonimoak": ["mugitu"]},
  {"id": "2-250", "hitza": "hilbeila", "sinonimoak": ["gaubeila", "beila"]},
  {"id": "2-251", "hitza": "hileko", "sinonimoak": ["soldata", "hileroko", "hilabeteko"]},
  {"id": "2-252", "hitza": "hiltzear", "sinonimoak": ["hilzorian", "hiletsian", "hiltamuan"]},
  {"id": "2-253", "hitza": "hirigune", "sinonimoak": ["erdigune", "erdialde"]},
  {"id": "2-254", "hitza": "hiritar", "sinonimoak": ["kaletar", "hiriko", "kaleko"]},
  {"id": "2-255", "hitza": "hisiti", "sinonimoak": ["burugogor", "setati", "tematsu"]},
  {"id": "2-256", "hitza": "hits", "sinonimoak": ["triste", "zurbil", "goibel"]},
  {"id": "2-257", "hitza": "hitz", "sinonimoak": ["berba", "ele", "solas"]},
  {"id": "2-258", "hitza": "hitzarmen", "sinonimoak": ["itun", "akordio", "tratu"]},
  {"id": "2-259", "hitza": "hitzaurre", "sinonimoak": ["aitzinsolas", "sarrera", "atariko"]},
  {"id": "2-260", "hitza": "hitzontzi", "sinonimoak": ["hiztun", "berritsu", "eleketari"]},
  {"id": "2-261", "hitza": "hizketa", "sinonimoak": ["berriketa", "eleketa", "berbeta"]},
  {"id": "2-262", "hitza": "hobari", "sinonimoak": ["etekin", "mozkin", "irabazi"]},
  {"id": "2-263", "hitza": "hobe ez", "sinonimoak": ["jakina", "bai horixe", "ezin uka"]},
  {"id": "2-264", "hitza": "hobendun", "sinonimoak": ["errudun", "egile", "kulpadun"]},
  {"id": "2-265", "hitza": "hobi", "sinonimoak": ["hilobi"]},
  {"id": "2-266", "hitza": "hondakin", "sinonimoak": ["zabor", "zakar", "zarama"]},
  {"id": "2-267", "hitza": "hondamen", "sinonimoak": ["hondamendi", "ausiabartza", "suntsitze"]},
  {"id": "2-268", "hitza": "hots", "sinonimoak": ["dei", "deiadar"]},
  {"id": "2-269", "hitza": "hunkigarri", "sinonimoak": ["zirraragarri"]},
  {"id": "2-270", "hitza": "hurko", "sinonimoak": ["ondoko", "alboko", "hurbileko"]},
  {"id": "2-271", "hitza": "huskeria", "sinonimoak": ["txikikeria", "ezerezkeria", "zirtzileria"]},
  {"id": "2-272", "hitza": "huts", "sinonimoak": ["kale"]},
  {"id": "2-273", "hitza": "iaio", "sinonimoak": ["trebe", "abil", "antzetsu"]},
  {"id": "2-274", "hitza": "ibilgu", "sinonimoak": ["korridore", "pasillo"]},
  {"id": "2-275", "hitza": "idoro", "sinonimoak": ["aurkitu", "ediren", "topatu"]},
  {"id": "2-276", "hitza": "idorte", "sinonimoak": ["lehorte", "sikate", "agorte"]},
  {"id": "2-277", "hitza": "igande", "sinonimoak": ["domeka"]},
  {"id": "2-278", "hitza": "igarri", "sinonimoak": ["asmatu", "antzeman", "sumatu"]},
  {"id": "2-279", "hitza": "igorri", "sinonimoak": ["bidali", "helarazi"]},
  {"id": "2-280", "hitza": "ihardetsi", "sinonimoak": ["erantzun", "kontra egin", "trabak jarri"]},
  {"id": "2-281", "hitza": "ihartu", "sinonimoak": ["zimeldu", "maskaldu", "zapuztu"]},
  {"id": "2-282", "hitza": "ikerketa", "sinonimoak": ["ikerkuntza", "ikertze", "ikerlan"]},
  {"id": "2-283", "hitza": "ikuskapen", "sinonimoak": ["ikuskatze", "miaketa", "araketa"]},
  {"id": "2-284", "hitza": "ikuspegi", "sinonimoak": ["panorama", "ikusmira", "bista"]},
  {"id": "2-285", "hitza": "ilemotots", "sinonimoak": ["iletxorta", "ile-txirikorda", "txirikorda"]},
  {"id": "2-286", "hitza": "ilundura", "sinonimoak": ["tristura", "nahigabe", "atsekabe"]},
  {"id": "2-287", "hitza": "iluntze", "sinonimoak": ["ilunabar", "ilunsenti", "gaualde"]},
  {"id": "2-288", "hitza": "imajina", "sinonimoak": ["eman", "jo", "pentsa"]},
  {"id": "2-289", "hitza": "imintzio", "sinonimoak": ["keinu"]},
  {"id": "2-290", "hitza": "inar", "sinonimoak": ["txinparta", "pindar", "txinka"]},
  {"id": "2-291", "hitza": "inarrosi", "sinonimoak": ["hunkitu", "astindu", "asaldatu"]},
  {"id": "2-292", "hitza": "inauteri", "sinonimoak": ["aratuste", "inaute"]},
  {"id": "2-293", "hitza": "indaba", "sinonimoak": ["babarrun", "mailar"]},
  {"id": "2-294", "hitza": "indarkeria", "sinonimoak": ["bortxakeria", "gogorkeria", "biolentzia"]},
  {"id": "2-295", "hitza": "indartu", "sinonimoak": ["sendotu", "bizkortu", "azkartu"]},
  {"id": "2-296", "hitza": "indriska", "sinonimoak": ["euri-jasa", "zaparrada", "zaldizko"]},
  {"id": "2-297", "hitza": "induskatu", "sinonimoak": ["hondeatu", "zulatu"]},
  {"id": "2-298", "hitza": "inguma", "sinonimoak": ["iratxo"]},
  {"id": "2-299", "hitza": "injustizia", "sinonimoak": ["bidegabekeria", "zuzengabekeria"]},
  {"id": "2-300", "hitza": "inkesta", "sinonimoak": ["galdeketa", "itaunketa"]}
];