import { WordData } from './types';

export const LEVEL_3_PART_3: WordData[] = [
  {"id": "3-201", "hitza": "nahita", "sinonimoak": ["gurata", "berariaz", "propio"]},
  {"id": "3-202", "hitza": "ñaka", "sinonimoak": ["txandrio", "engainu", "iruzur"]},
  {"id": "3-203", "hitza": "nakan", "sinonimoak": ["orezta", "orin", "natu"]},
  {"id": "3-204", "hitza": "narrio", "sinonimoak": ["akats", "oker", "hutsegite"]},
  {"id": "3-205", "hitza": "nasai", "sinonimoak": ["zabal", "lasai", "arin"]},
  {"id": "3-206", "hitza": "natura", "sinonimoak": ["izadi"]},
  {"id": "3-207", "hitza": "ñau", "sinonimoak": ["miau", "marraka", "mau"]},
  {"id": "3-208", "hitza": "nazkagarri", "sinonimoak": ["higuingarri", "nardagarri"]},
  {"id": "3-209", "hitza": "negargarri", "sinonimoak": ["zoritxar", "ezbehar", "malur", "zorigaitz"]},
  {"id": "3-210", "hitza": "nekez", "sinonimoak": ["ozta-ozta", "zailki", "kostata"]},
  {"id": "3-211", "hitza": "nerabetasun", "sinonimoak": ["nerabezaro", "adoleszentzia"]},
  {"id": "3-212", "hitza": "neroni", "sinonimoak": ["neuri"]},
  {"id": "3-213", "hitza": "neurriko", "sinonimoak": ["tamainako", "moduko", "dimentsioko"]},
  {"id": "3-214", "hitza": "neurtezin", "sinonimoak": ["neurge"]},
  {"id": "3-215", "hitza": "nihaur", "sinonimoak": ["neu", "nerau"]},
  {"id": "3-216", "hitza": "niketz", "sinonimoak": ["nire partez", "nire aldetik", "nire izenean"]},
  {"id": "3-217", "hitza": "ñiki-ñaka", "sinonimoak": ["txortan", "larrutan", "txikili-txakala"]},
  {"id": "3-218", "hitza": "ñimiño", "sinonimoak": ["ñarro", "txiki", "ttipi"]},
  {"id": "3-219", "hitza": "ninikatu", "sinonimoak": ["kimatu", "muskildu", "ernamuindu"]},
  {"id": "3-220", "hitza": "ninikeria", "sinonimoak": ["umekeria", "haurkeria", "seinkeria"]},
  {"id": "3-221", "hitza": "ñir-ñir", "sinonimoak": ["dir-dir", "diz-diz"]},
  {"id": "3-222", "hitza": "nobedade", "sinonimoak": ["berri", "albiste"]},
  {"id": "3-223", "hitza": "nobela", "sinonimoak": ["eleberri"]},
  {"id": "3-224", "hitza": "noharroin", "sinonimoak": ["behartsu", "txiro", "pobre"]},
  {"id": "3-225", "hitza": "noiznahi", "sinonimoak": ["edonoiz", "noiznahi den", "noizgura"]},
  {"id": "3-226", "hitza": "noiztik", "sinonimoak": ["noizdanik"]},
  {"id": "3-227", "hitza": "noku", "sinonimoak": ["akats", "hutsune", "gabezia", "narrio"]},
  {"id": "3-228", "hitza": "nolakatu", "sinonimoak": ["bihurtu", "bilakatu", "aldatu"]},
  {"id": "3-229", "hitza": "nolakotasun", "sinonimoak": ["ezaugarri", "tasun", "dohain"]},
  {"id": "3-230", "hitza": "nolanahiko", "sinonimoak": ["edonolako", "edozein", "halako"]},
  {"id": "3-231", "hitza": "nongotasun", "sinonimoak": ["jatorri", "sorleku", "sorterri"]},
  {"id": "3-232", "hitza": "nonzerberri", "sinonimoak": ["kontakatilu", "autubatzaile", "eleberritsu"]},
  {"id": "3-233", "hitza": "norabide", "sinonimoak": ["noranzko", "norako"]},
  {"id": "3-234", "hitza": "norgehiagoka", "sinonimoak": ["partida", "norlehenka", "lehia"]},
  {"id": "3-235", "hitza": "normalean", "sinonimoak": ["oro har", "eskuarki"]},
  {"id": "3-236", "hitza": "nortasun", "sinonimoak": ["izaera", "jite", "aiurri"]},
  {"id": "3-237", "hitza": "nozitu", "sinonimoak": ["pairatu", "jasan", "sufritu"]},
  {"id": "3-238", "hitza": "objektore", "sinonimoak": ["eragozle"]},
  {"id": "3-239", "hitza": "obratu", "sinonimoak": ["libratu", "sabelustu", "kaka egin"]},
  {"id": "3-240", "hitza": "odolatu", "sinonimoak": ["ubeldu", "ubeldura", "beltzune"]},
  {"id": "3-241", "hitza": "odolbero", "sinonimoak": ["haserrekor", "suminkor", "suhar"]},
  {"id": "3-242", "hitza": "odolki", "sinonimoak": ["odoloste", "tripot", "tripotx"]},
  {"id": "3-243", "hitza": "ofizio", "sinonimoak": ["lanbide", "ogibide", "bizibide"]},
  {"id": "3-244", "hitza": "ogasundun", "sinonimoak": ["aberats", "ondasundun", "ukandun"]},
  {"id": "3-245", "hitza": "ohaide", "sinonimoak": ["ohelagun", "amorante", "maitale"]},
  {"id": "3-246", "hitza": "ohargarriki", "sinonimoak": ["nabarmenki", "nabariki", "argiro"]},
  {"id": "3-247", "hitza": "oharkabekeria", "sinonimoak": ["axolagabekeria", "arduragabekeria", "zabarkeria"]},
  {"id": "3-248", "hitza": "oharpen", "sinonimoak": ["ohar", "gaztigu", "oharkizun"]},
  {"id": "3-249", "hitza": "ohildu", "sinonimoak": ["uxatu", "aienatu", "izutu"]},
  {"id": "3-250", "hitza": "ohitura", "sinonimoak": ["usadio", "aztura", "ekandu"]},
  {"id": "3-251", "hitza": "ohoin", "sinonimoak": ["lapur", "ebasle"]},
  {"id": "3-252", "hitza": "oies", "sinonimoak": ["latz", "trauskil", "zakar"]},
  {"id": "3-253", "hitza": "oiher", "sinonimoak": ["bihurri", "oker", "makur"]},
  {"id": "3-254", "hitza": "oihu", "sinonimoak": ["garrasi", "deiadar", "txilio", "heiagora"]},
  {"id": "3-255", "hitza": "oilotu", "sinonimoak": ["koldartu", "kikildu", "uzkurtu"]},
  {"id": "3-256", "hitza": "oinarri", "sinonimoak": ["funts", "harroin", "abiaburu"]},
  {"id": "3-257", "hitza": "oinatz", "sinonimoak": ["aztarna", "zantzu", "arrasto"]},
  {"id": "3-258", "hitza": "oinazegarri", "sinonimoak": ["mingarri", "samingarri", "atsekabegarri"]},
  {"id": "3-259", "hitza": "oinaztargi", "sinonimoak": ["tximistargi", "tximista", "oinaztarri"]},
  {"id": "3-260", "hitza": "oinordeko", "sinonimoak": ["jabegai", "jaraunsle"]},
  {"id": "3-261", "hitza": "oinutsik", "sinonimoak": ["ortozik", "hanka hutsik", "zankuts"]},
  {"id": "3-262", "hitza": "okaztagarri", "sinonimoak": ["kirasdun", "nazkagarri", "higuingarri"]},
  {"id": "3-263", "hitza": "okela", "sinonimoak": ["haragi", "haragiki", "txitxi"]},
  {"id": "3-264", "hitza": "oker", "sinonimoak": ["erratuta", "tronpatuta", "alferrik"]},
  {"id": "3-265", "hitza": "okerragotu", "sinonimoak": ["areagotu", "larriagotu", "gaizkiagotu"]},
  {"id": "3-266", "hitza": "olagarro", "sinonimoak": ["eskuluze"]},
  {"id": "3-267", "hitza": "oldarkor", "sinonimoak": ["grinatsu", "gartsu", "suhar"]},
  {"id": "3-268", "hitza": "oldozketa", "sinonimoak": ["gogoeta", "hausnarketa", "pentsaketa"]},
  {"id": "3-269", "hitza": "olerkigintza", "sinonimoak": ["poemagintza", "poesiagintza"]},
  {"id": "3-270", "hitza": "omenaldi", "sinonimoak": ["gorazarre"]},
  {"id": "3-271", "hitza": "onartu", "sinonimoak": ["onetsi", "aitortu", "baietsi"]},
  {"id": "3-272", "hitza": "onbehar", "sinonimoak": ["pobrezia", "miseria", "txirotasun"]},
  {"id": "3-273", "hitza": "onbera", "sinonimoak": ["onegi", "on hutsa", "bihozbera"]},
  {"id": "3-274", "hitza": "ondare", "sinonimoak": ["oinorde", "ondorego", "jaraunspen"]},
  {"id": "3-275", "hitza": "ondikoz", "sinonimoak": ["tamalez", "zoritxarrez", "maluruski"]},
  {"id": "3-276", "hitza": "ondoko", "sinonimoak": ["alboko", "aldameneko", "pareko"]},
  {"id": "3-277", "hitza": "ondu", "sinonimoak": ["hobetu", "hobekitu", "oneratu"]},
  {"id": "3-278", "hitza": "oniritzi", "sinonimoak": ["onespen", "onarpen", "baimen"]},
  {"id": "3-279", "hitza": "ontsa", "sinonimoak": ["ongi", "ederki"]},
  {"id": "3-280", "hitza": "onturre", "sinonimoak": ["onura", "probetxu", "etekin"]},
  {"id": "3-281", "hitza": "oparotasun", "sinonimoak": ["ugaritasun", "joritasun", "narotasun"]},
  {"id": "3-282", "hitza": "oratu", "sinonimoak": ["heldu", "lotu", "eutsi"]},
  {"id": "3-283", "hitza": "ordaindu", "sinonimoak": ["jasan", "pairatu", "sufritu"]},
  {"id": "3-284", "hitza": "ordea", "sinonimoak": ["ostera", "aldiz", "berriz"]},
  {"id": "3-285", "hitza": "orobat", "sinonimoak": ["halaber", "era berean"]},
  {"id": "3-286", "hitza": "oroipen", "sinonimoak": ["oroitzapen", "gogorapen", "gomuta"]},
  {"id": "3-287", "hitza": "oroipen", "sinonimoak": ["oroitzapen", "gogorapen", "gomuta"]},
  {"id": "3-288", "hitza": "orraztu", "sinonimoak": ["orrazketa", "berrikuspen", "gainbegiratu"]},
  {"id": "3-289", "hitza": "orraztu", "sinonimoak": ["orrazketa", "berrikuste", "gainbegiratu"]},
  {"id": "3-290", "hitza": "osoro", "sinonimoak": ["osorik", "guztiz", "goraino"]},
  {"id": "3-291", "hitza": "ospetsu", "sinonimoak": ["entzutetsu", "sonatu", "aipatu"]},
  {"id": "3-292", "hitza": "ospetsu", "sinonimoak": ["entzutetsu", "sonatu", "aipatu"]},
  {"id": "3-293", "hitza": "ospitale", "sinonimoak": ["erietxe", "eritegi"]},
  {"id": "3-294", "hitza": "ospitale", "sinonimoak": ["erietxe", "eritegi"]},
  {"id": "3-295", "hitza": "ostiral", "sinonimoak": ["bariku", "ortziral"]},
  {"id": "3-296", "hitza": "ostiral", "sinonimoak": ["bariku", "ortziral"]},
  {"id": "3-297", "hitza": "otoi", "sinonimoak": ["mesedez", "arren", "faborez"]},
  {"id": "3-298", "hitza": "otu", "sinonimoak": ["bururatu"]},
  {"id": "3-299", "hitza": "otzandu", "sinonimoak": ["mantsotu", "hezi", "menderatu"]},
  {"id": "3-300", "hitza": "otzara", "sinonimoak": ["saski", "otarre", "zare"]}
];