import { WordData } from './types';

export const LEVEL_2_PART_2: WordData[] = [
  {"id": "2-101", "hitza": "doi-doi", "sinonimoak": ["ozta-ozta", "justu-justu"]},
  {"id": "2-102", "hitza": "doilortu", "sinonimoak": ["zitaldu", "zakartu", "petraldu"]},
  {"id": "2-103", "hitza": "donge", "sinonimoak": ["txar", "gaizto", "maltzur"]},
  {"id": "2-104", "hitza": "dorpe", "sinonimoak": ["trakets", "baldar", "baldres"]},
  {"id": "2-105", "hitza": "dotore", "sinonimoak": ["apain", "lirain", "txiro"]},
  {"id": "2-106", "hitza": "dragoi", "sinonimoak": ["herensuge"]},
  {"id": "2-107", "hitza": "drolekeria", "sinonimoak": ["txantxa", "broma", "olgeta"]},
  {"id": "2-108", "hitza": "duda", "sinonimoak": ["zalantza", "ezbai"]},
  {"id": "2-109", "hitza": "dunbots", "sinonimoak": ["zarata", "zalaparta", "azantz"]},
  {"id": "2-110", "hitza": "dungulu", "sinonimoak": ["morokil", "ahi"]},
  {"id": "2-111", "hitza": "durduzadura", "sinonimoak": ["nahasmendu", "nahaste", "laborri"]},
  {"id": "2-112", "hitza": "dutxulu", "sinonimoak": ["txorrot", "iturri", "kanila"]},
  {"id": "2-113", "hitza": "ebakera", "sinonimoak": ["ahoskera", "ahoskatze", "ahoskuntza"]},
  {"id": "2-114", "hitza": "ebakuntza", "sinonimoak": ["ebaketa", "operazio"]},
  {"id": "2-115", "hitza": "ebatsi", "sinonimoak": ["lapurtu", "ostu"]},
  {"id": "2-116", "hitza": "ebazpen", "sinonimoak": ["erabaki", "burubide", "xedapen"]},
  {"id": "2-117", "hitza": "edagale", "sinonimoak": ["egarri"]},
  {"id": "2-118", "hitza": "edendu", "sinonimoak": ["pozoitu"]},
  {"id": "2-119", "hitza": "ederki", "sinonimoak": ["ederto", "bapo", "primeran"]},
  {"id": "2-120", "hitza": "ederretsi", "sinonimoak": ["preziatu", "balioetsi", "estimatu"]},
  {"id": "2-121", "hitza": "edertu", "sinonimoak": ["liraindu", "zirastu", "ederreztatu"]},
  {"id": "2-122", "hitza": "edonor", "sinonimoak": ["nornahi", "edozein", "zeinahi"]},
  {"id": "2-123", "hitza": "edukazio", "sinonimoak": ["heziketa", "gizabide", "heziera"]},
  {"id": "2-124", "hitza": "egia-egiatan", "sinonimoak": ["bene-benetan", "zinez", "alafede"]},
  {"id": "2-125", "hitza": "egiaztagiri", "sinonimoak": ["ziurtagiri", "frogagiri", "egiaztagarri"]},
  {"id": "2-126", "hitza": "egikaritu", "sinonimoak": ["betearazi", "burutu", "obratu"]},
  {"id": "2-127", "hitza": "eginahal", "sinonimoak": ["ahalegin", "esfortzu", "entsegu"]},
  {"id": "2-128", "hitza": "eginkizun", "sinonimoak": ["betebehar", "zeregin", "lan"]},
  {"id": "2-129", "hitza": "egituratu", "sinonimoak": ["programatu", "eratu", "antolatu"]},
  {"id": "2-130", "hitza": "egoiliar", "sinonimoak": ["bizilagun", "etxetiar", "maizter"]},
  {"id": "2-131", "hitza": "egokiera", "sinonimoak": ["aukera", "parada", "abagune"]},
  {"id": "2-132", "hitza": "egonezin", "sinonimoak": ["urduritasun", "artegatasun", "kezka"]},
  {"id": "2-133", "hitza": "egonkor", "sinonimoak": ["iraunkor", "finko"]},
  {"id": "2-134", "hitza": "egoskor", "sinonimoak": ["setati", "burugogor", "tematsu"]},
  {"id": "2-135", "hitza": "egotetxe", "sinonimoak": ["aterpetxe", "ostatu", "babesleku"]},
  {"id": "2-136", "hitza": "egotzi", "sinonimoak": ["leporatu", "bota", "gaineratu"]},
  {"id": "2-137", "hitza": "egunabar", "sinonimoak": ["egunsenti", "goizalde", "goiztiri"]},
  {"id": "2-138", "hitza": "egundoko", "sinonimoak": ["sekulako", "izugarrizko", "itzelezko"]},
  {"id": "2-139", "hitza": "ehortzi", "sinonimoak": ["lurperatu", "hobiratu"]},
  {"id": "2-140", "hitza": "eihera", "sinonimoak": ["errota", "bolu"]},
  {"id": "2-141", "hitza": "eite", "sinonimoak": ["itxura", "irudi", "jite"]},
  {"id": "2-142", "hitza": "ekain", "sinonimoak": ["bagil", "ereiaro"]},
  {"id": "2-143", "hitza": "ekoizle", "sinonimoak": ["sortzaile", "produzitzaile", "produktore"]},
  {"id": "2-144", "hitza": "ekortu", "sinonimoak": ["erraztatu", "eskobatu", "erratzez garbitu"]},
  {"id": "2-145", "hitza": "ekuru", "sinonimoak": ["lasai", "trankil", "patxadatsu"]},
  {"id": "2-146", "hitza": "elai", "sinonimoak": ["enara"]},
  {"id": "2-147", "hitza": "enbarazu", "sinonimoak": ["traba", "oztopo", "eragozpen"]},
  {"id": "2-148", "hitza": "enparau", "sinonimoak": ["gainerako", "gainontzeko", "uzkin"]},
  {"id": "2-149", "hitza": "entzun", "sinonimoak": ["aditu"]},
  {"id": "2-150", "hitza": "entzutetsu", "sinonimoak": ["ospetsu", "famatu", "sonatu"]},
  {"id": "2-151", "hitza": "erabaki", "sinonimoak": ["zirt edo zart egin", "ebatzi", "xedatu"]},
  {"id": "2-152", "hitza": "erabat", "sinonimoak": ["guztiz", "zeharo", "arras"]},
  {"id": "2-153", "hitza": "erabilgarri", "sinonimoak": ["maneiagarri", "erabilerraz", "maneiukor"]},
  {"id": "2-154", "hitza": "eragin", "sinonimoak": ["sorrarazi", "izanarazi", "edukiarazi"]},
  {"id": "2-155", "hitza": "eragotzi", "sinonimoak": ["galarazi", "debekatu", "oztopatu"]},
  {"id": "2-156", "hitza": "erakusleiho", "sinonimoak": ["erakustoki"]},
  {"id": "2-157", "hitza": "eranskin", "sinonimoak": ["gehigarri", "osagarri"]},
  {"id": "2-158", "hitza": "erbeste", "sinonimoak": ["deserri", "atzerri"]},
  {"id": "2-159", "hitza": "erbinude", "sinonimoak": ["ogigazta"]},
  {"id": "2-160", "hitza": "erdeinagarri", "sinonimoak": ["mespretxagarri", "gaitzesgarri", "baztergarri"]},
  {"id": "2-161", "hitza": "erdietsi", "sinonimoak": ["lortu", "eskuratu", "jadetsi"]},
  {"id": "2-162", "hitza": "ergel", "sinonimoak": ["lelo", "tentel", "kaiku"]},
  {"id": "2-163", "hitza": "erpin", "sinonimoak": ["tontor", "gailur", "gain"]},
  {"id": "2-164", "hitza": "errieta", "sinonimoak": ["haserre", "agiraka", "ahakar"]},
  {"id": "2-165", "hitza": "erruki", "sinonimoak": ["gupida", "urrikalmendu", "errukitasun"]},
  {"id": "2-166", "hitza": "etxekotu", "sinonimoak": ["bertakotu", "lekukotu", "tokikotu"]},
  {"id": "2-167", "hitza": "eutsi", "sinonimoak": ["heldu", "oratu", "lotu"]},
  {"id": "2-168", "hitza": "ezetsi", "sinonimoak": ["ukatu", "baztertu", "errefusatu"]},
  {"id": "2-169", "hitza": "ezinbestez", "sinonimoak": ["halabeharrez", "nahitaez", "derrigorrean"]},
  {"id": "2-170", "hitza": "ezinikusi", "sinonimoak": ["gorroto", "herra", "higuin"]},
  {"id": "2-171", "hitza": "ezizen", "sinonimoak": ["goitizen", "izengoiti", "gaitzizen"]},
  {"id": "2-172", "hitza": "ezuste", "sinonimoak": ["ustekabe"]},
  {"id": "2-173", "hitza": "faborez", "sinonimoak": ["mesedez", "arren", "otoi"]},
  {"id": "2-174", "hitza": "falta", "sinonimoak": ["gabezia", "ez", "eskasia"]},
  {"id": "2-175", "hitza": "fama", "sinonimoak": ["ospe", "entzute", "omen"]},
  {"id": "2-176", "hitza": "familiarteko", "sinonimoak": ["familiako", "senitarteko", "ahaide"]},
  {"id": "2-177", "hitza": "fededun", "sinonimoak": ["sinestedun", "sinestun", "sinesle"]},
  {"id": "2-178", "hitza": "fereka", "sinonimoak": ["laztan", "txera"]},
  {"id": "2-179", "hitza": "festa", "sinonimoak": ["jai", "besta"]},
  {"id": "2-180", "hitza": "fidel", "sinonimoak": ["leial", "zintzo", "on"]},
  {"id": "2-181", "hitza": "fildak", "sinonimoak": ["zarpailak", "piltzarrak", "zarpak"]},
  {"id": "2-182", "hitza": "fin", "sinonimoak": ["trebe", "zintzo", "on"]},
  {"id": "2-183", "hitza": "finkatu", "sinonimoak": ["ezarri", "zehaztu", "mugatu"]},
  {"id": "2-184", "hitza": "finko", "sinonimoak": ["tinko", "irmo", "zurrun"]},
  {"id": "2-185", "hitza": "fitsik", "sinonimoak": ["tutik", "deusik", "zipitzik"]},
  {"id": "2-186", "hitza": "flakatu", "sinonimoak": ["argaldu", "mehetu", "lerdendu"]},
  {"id": "2-187", "hitza": "flako", "sinonimoak": ["ahul", "makal", "indarge"]},
  {"id": "2-188", "hitza": "formal", "sinonimoak": ["zintzo", "zentzudun", "prestu"]},
  {"id": "2-189", "hitza": "franko", "sinonimoak": ["asko", "ugari", "anitz"]},
  {"id": "2-190", "hitza": "fresko", "sinonimoak": ["hozkirri", "hozgiro", "freskura"]},
  {"id": "2-191", "hitza": "frogatu", "sinonimoak": ["egiaztatu", "ziurtatu", "adierazi"]},
  {"id": "2-192", "hitza": "funts", "sinonimoak": ["oinarri", "zentzu", "zimendu"]},
  {"id": "2-193", "hitza": "gabe(rik)", "sinonimoak": ["barik", "gabetarik"]},
  {"id": "2-194", "hitza": "Gabon(ak)", "sinonimoak": ["Eguberri(ak)"]},
  {"id": "2-195", "hitza": "gailendu", "sinonimoak": ["nagusitu", "nabarmendu"]},
  {"id": "2-196", "hitza": "gain", "sinonimoak": ["gainera", "leko(ra)", "landa(ra)"]},
  {"id": "2-197", "hitza": "gainazal", "sinonimoak": ["azalera", "gainalde", "hedadura"]},
  {"id": "2-198", "hitza": "gaineratu", "sinonimoak": ["gehitu", "erantsi"]},
  {"id": "2-199", "hitza": "gaitasun", "sinonimoak": ["trebetasun", "iaiotasun", "abilezia"]},
  {"id": "2-200", "hitza": "gaitu", "sinonimoak": ["prestatu", "gertatu", "egokitu"]}
];